EXTEND_ACHIEVEMENT(左右逢源, "不指定种子的情况下，在所有线路上的牌型均非高牌")
EXTEND_ACHIEVEMENT(入门收藏家, "不指定种子的情况下，除高牌外的牌型种类达到 6")
EXTEND_ACHIEVEMENT(收藏家, "不指定种子的情况下，除高牌外的牌型种类达到 7")
EXTEND_ACHIEVEMENT(专业收藏家, "不指定种子的情况下，除高牌外的牌型种类达到 8")
EXTEND_ACHIEVEMENT(皇家同花顺, "不指定种子的情况下，形成皇家同花顺牌型")
EXTEND_ACHIEVEMENT(渐入佳境, "不指定种子的情况下，分数达到 1200 分")
EXTEND_ACHIEVEMENT(得心应手, "不指定种子的情况下，分数达到 1600 分")
EXTEND_ACHIEVEMENT(出神入化, "不指定种子的情况下，分数达到 2000 分")
EXTEND_ACHIEVEMENT(天人合一, "不指定种子的情况下，分数达到 2400 分")
