target_link_libraries(sync_mahjong Mahjong MahjongAlgorithm)
add_dependencies(sync_mahjong Mahjong MahjongAlgorithm)
if (WITH_TEST)
    target_link_libraries(test_game_sync_mahjong Mahjong MahjongAlgorithm)
    add_dependencies(test_game_sync_mahjong Mahjong MahjongAlgorithm)
    target_link_libraries(run_game_sync_mahjong Mahjong MahjongAlgorithm)
    add_dependencies(run_game_sync_mahjong Mahjong MahjongAlgorithm)
endif()
