EXTEND_ACHIEVEMENT(国士无双, "和牌时带有「国士无双」或「国士无双十三面」一役")
EXTEND_ACHIEVEMENT(九莲宝灯, "和牌时带有「九莲宝灯」或「纯正九莲宝灯」一役")
EXTEND_ACHIEVEMENT(字一色, "和牌时带有「字一色」一役")
EXTEND_ACHIEVEMENT(小四喜, "和牌时带有「小四喜」一役")
EXTEND_ACHIEVEMENT(大四喜, "和牌时带有「大四喜」一役")
EXTEND_ACHIEVEMENT(大三元, "和牌时带有「大三元」一役")
EXTEND_ACHIEVEMENT(清老头, "和牌时带有「清老头」一役")
EXTEND_ACHIEVEMENT(四暗刻, "和牌时带有「四暗刻」一役")
EXTEND_ACHIEVEMENT(绿一色, "和牌时带有「绿一色」一役")
EXTEND_ACHIEVEMENT(累计役满, "和牌时番数达到 13 番及以上")
