EXTEND_OPTION("回合数", 回合数, (ArithChecker<uint32_t>(1, 40, "回合数")), 40)
EXTEND_OPTION("每回合时间限制", 时限, (ArithChecker<uint32_t>(10, 3600, "超时时间（秒）")), 120)
EXTEND_OPTION("最大可提交数字", 最大数字, (ArithChecker<uint32_t>(5, 10000, "最大数字")), 100)
EXTEND_OPTION("玩家初始血量", 血量, (ArithChecker<uint32_t>(1, 30, "血量")), 10)
EXTEND_OPTION("开启玩家 [撞车] 时额外损失生命值", 撞车伤害, (BoolChecker("开启", "关闭")), true)
EXTEND_OPTION("在最终3人规则下，是否开启 100 直接淘汰 0", 淘汰规则, (BoolChecker("开启", "关闭")), true)
EXTEND_OPTION("设置 [撞车] 特则出现的回合数（0 视为不开启此规则）", 撞车, (ArithChecker<uint32_t>(0, 40, "回合数")), 4)
EXTEND_OPTION("设置 [红心] 特则出现的回合数（0 视为不开启此规则）", 红心, (ArithChecker<uint32_t>(0, 40, "回合数")), 6)