EXTEND_ACHIEVEMENT(悄无声息, "未发出任何声响的情况下乘坐逃生舱")
EXTEND_ACHIEVEMENT(环游世界, "探索地图中的每一个区块")
EXTEND_ACHIEVEMENT(游荡幽灵, "未发出任何声响的情况下，探索地图中的每一个区块")
EXTEND_ACHIEVEMENT(我赶时间, "在第一回合乘坐逃生舱")
EXTEND_ACHIEVEMENT(饥渴难耐, "在第一回合捕捉目标玩家")
EXTEND_ACHIEVEMENT(乒铃乓啷, "路过或触发 5 种及以上不同的地形")
EXTEND_ACHIEVEMENT(嗜杀成性, "4人及以上对局中，捕捉所有其他玩家")
EXTEND_ACHIEVEMENT(守株待兔, "在单个回合中未进行移动并成功捕捉目标玩家")
EXTEND_ACHIEVEMENT(牛头魅魔, "持续被米诺陶斯锁定，BOSS移动 3 步仍未被抓到")
