EXTEND_OPTION("放置阶段时间限制（总时间限制）", 放置时限, (ArithChecker<uint32_t>(10, 3600, "超时时间（秒）")), 300)
EXTEND_OPTION("进攻阶段时间限制（进攻操作每一步的时间限制）", 进攻时限, (ArithChecker<uint32_t>(10, 3600, "超时时间（秒）")), 120)
EXTEND_OPTION("设置地图大小", 边长, (ArithChecker<uint32_t>(8, 15, "边长")), 10)
EXTEND_OPTION("设置飞机数量", 飞机, (ArithChecker<uint32_t>(1, 8, "数量")), 3)
EXTEND_OPTION("是否允许飞机互相重叠", 重叠, (BoolChecker("允许", "不允许")), false)
EXTEND_OPTION("连发次数", 连发, (ArithChecker<uint32_t>(1, 10, "次数")), 3)
EXTEND_OPTION("初始随机侦察区域大小（默认为随机）", 侦察, (ArithChecker<uint32_t>(0, 30, "面积")), 100)
EXTEND_OPTION("设置命中要害是否有提示", 要害, AlterChecker<int>({{"有", 0}, {"无", 1}, {"首次", 2}}), 0)
EXTEND_OPTION("BOSS挑战模式：用于挑战特殊配置的BOSS战", BOSS挑战, (ArithChecker<uint32_t>(0, 1, "模式")), 0)
