EXTEND_ACHIEVEMENT(蜂巢开拓者, "在不指定种子的前提下，地图上未联通的线路仅剩 2 条")
EXTEND_ACHIEVEMENT(蜂巢编织者, "在不指定种子的前提下，地图上未联通的线路仅剩 1 条")
EXTEND_ACHIEVEMENT(蜂巢完美者, "在不指定种子的前提下，成功联通地图上的每一条线路")
EXTEND_ACHIEVEMENT(经典开篇, "无种子且使用传统模式[经典]卡池，基础分达到 250 分及以上")
EXTEND_ACHIEVEMENT(不凡经典, "无种子且使用传统模式[经典]卡池，基础分达到 300 分及以上")
EXTEND_ACHIEVEMENT(传世经典, "无种子且使用传统模式[经典]卡池，基础分达到 350 分及以上")
EXTEND_ACHIEVEMENT(万象归一, "无种子且使用传统模式[癞子]卡池，基础分达到 350 分及以上")
EXTEND_ACHIEVEMENT(空灵之境, "无种子且使用传统模式[空气]卡池，基础分达到 250 分及以上")
EXTEND_ACHIEVEMENT(乱象初现, "无种子且使用传统模式[混乱]卡池，基础分达到 250 分及以上")
EXTEND_ACHIEVEMENT(破碎旅程, "无种子且使用传统模式[混乱]卡池，基础分达到 300 分及以上")
EXTEND_ACHIEVEMENT(混乱主宰, "无种子且使用传统模式[混乱]卡池，基础分达到 350 分及以上")
EXTEND_ACHIEVEMENT(空中楼阁, "无种子且使用[空气]或[混乱]卡池，联通所有的空气线路")
EXTEND_ACHIEVEMENT(十全十美, "无种子且使用[癞子]或[混乱]卡池，获得第一名且所有癞子线均为10分")
EXTEND_ACHIEVEMENT(贯穿星河, "在不指定种子的前提下，成功联通一条长度为 9 的线路")