EXTEND_ACHIEVEMENT(天赋蜂王, "在不指定种子的前提下，联通 15 条线路")
EXTEND_ACHIEVEMENT(天赋满溢, "在不指定种子的前提下，获得 6 个及以上的天赋")
EXTEND_ACHIEVEMENT(天赋初启, "在不指定种子的前提下，获得 300 分及以上的总分")
EXTEND_ACHIEVEMENT(天赋进阶, "在不指定种子的前提下，获得 340 分及以上的总分")
EXTEND_ACHIEVEMENT(天赋精通, "在不指定种子的前提下，获得 380 分及以上的总分")
EXTEND_ACHIEVEMENT(常胜将军, "在不指定种子的前提下，获得最终胜利且从未在对战中失败")
EXTEND_ACHIEVEMENT(命悬一线, "在不指定种子的前提下，获得最终胜利且剩余血量为 1")
EXTEND_ACHIEVEMENT(先发制人, "在不指定种子的前提下，在第一轮选牌前获得天赋")
EXTEND_ACHIEVEMENT(癞子长虹, "在不指定种子的前提下，连成一条长度为 5 的癞子线")
EXTEND_ACHIEVEMENT(天选之数, "在不指定种子的前提下，盘面所有格子都包含同一个数字")
