EXTEND_ACHIEVEMENT(国士无双, "不指定种子且四人游戏的情况下，和牌时带有「国士无双」」一役")
EXTEND_ACHIEVEMENT(国士无双十三面, "不指定种子且四人游戏的情况下，和牌时带有「国士无双十三面」一役")
EXTEND_ACHIEVEMENT(九莲宝灯, "不指定种子且四人游戏的情况下，和牌时带有「九莲宝灯」一役")
EXTEND_ACHIEVEMENT(纯正九莲宝灯, "不指定种子且四人游戏的情况下，和牌时带有「纯正九莲宝灯」一役")
EXTEND_ACHIEVEMENT(字一色, "不指定种子且四人游戏的情况下，和牌时带有「字一色」一役")
EXTEND_ACHIEVEMENT(小四喜, "不指定种子且四人游戏的情况下，和牌时带有「小四喜」一役")
EXTEND_ACHIEVEMENT(大四喜, "不指定种子且四人游戏的情况下，和牌时带有「大四喜」一役")
EXTEND_ACHIEVEMENT(大三元, "不指定种子且四人游戏的情况下，和牌时带有「大三元」一役")
EXTEND_ACHIEVEMENT(清老头, "不指定种子且四人游戏的情况下，和牌时带有「清老头」一役")
EXTEND_ACHIEVEMENT(四暗刻, "不指定种子且四人游戏的情况下，和牌时带有「四暗刻」一役")
EXTEND_ACHIEVEMENT(四暗刻单骑, "不指定种子且四人游戏的情况下，和牌时带有「四暗刻单骑」一役")
EXTEND_ACHIEVEMENT(绿一色, "不指定种子且四人游戏的情况下，和牌时带有「绿一色」一役")
EXTEND_ACHIEVEMENT(天和, "不指定种子的情况下，和牌时带有「天和」一役")
EXTEND_ACHIEVEMENT(累计役满, "不指定种子且四人游戏的情况下，和牌时番数达到 13 番及以上")

EXTEND_ACHIEVEMENT(流局满贯, "不指定种子的情况下，荒牌流局时自己仅切过幺九牌")

EXTEND_ACHIEVEMENT(清一色, "不指定种子且四人游戏的情况下，和牌时带有「清一色」一役，允许鸣牌")

EXTEND_ACHIEVEMENT(二杯口, "不指定种子且四人游戏的情况下，和牌时带有「二杯口」一役")
EXTEND_ACHIEVEMENT(纯全带幺九, "不指定种子且四人游戏的情况下，和牌时带有「纯全带幺九」一役，允许鸣牌")

EXTEND_ACHIEVEMENT(七对子, "不指定种子且四人游戏的情况下，和牌时带有「七对子」一役")
EXTEND_ACHIEVEMENT(混全带幺九, "不指定种子且四人游戏的情况下，和牌时带有「混全带幺九」一役，允许鸣牌")
EXTEND_ACHIEVEMENT(三色同刻, "不指定种子且四人游戏的情况下，和牌时带有「三色同刻」一役")
EXTEND_ACHIEVEMENT(三暗刻, "不指定种子且四人游戏的情况下，和牌时带有「三暗刻」一役")
EXTEND_ACHIEVEMENT(一气通贯, "不指定种子且四人游戏的情况下，和牌时带有「一气通贯」一役，允许鸣牌")
EXTEND_ACHIEVEMENT(三色同顺, "不指定种子且四人游戏的情况下，和牌时带有「三色同顺」一役，允许鸣牌")
EXTEND_ACHIEVEMENT(混老头, "不指定种子且四人游戏的情况下，和牌时带有「混老头」一役")
EXTEND_ACHIEVEMENT(三杠子, "不指定种子且四人游戏的情况下，和牌时带有「三杠子」一役")
EXTEND_ACHIEVEMENT(小三元, "不指定种子且四人游戏的情况下，和牌时带有「小三元」一役")
EXTEND_ACHIEVEMENT(两立直, "不指定种子且四人游戏的情况下，和牌时带有「两立直」一役")

EXTEND_ACHIEVEMENT(河底捞鱼, "不指定种子的情况下，和牌时带有「河底捞鱼」一役")
EXTEND_ACHIEVEMENT(海底捞月, "不指定种子的情况下，和牌时带有「海底捞月」一役")
EXTEND_ACHIEVEMENT(岭上开花, "不指定种子的情况下，和牌时带有「岭上开花」一役")
EXTEND_ACHIEVEMENT(抢杠, "不指定种子的情况下，和牌时带有「抢杠」一役")

EXTEND_ACHIEVEMENT(四风连打, "不指定种子的情况下，触发四风连打流局")
EXTEND_ACHIEVEMENT(三家和了, "不指定种子的情况下，宣告和牌时触发三家和了流局")
