EXTEND_ACHIEVEMENT(满载而归, "单局带回 100 枚及以上金币")
EXTEND_ACHIEVEMENT(珠光宝气, "独自撤离，一次带走 3 件及以上珍宝")
EXTEND_ACHIEVEMENT(稀世珍宝, "独自撤离，带走一件价值 30 及以上的珍宝")
EXTEND_ACHIEVEMENT(虎口脱险, "撤离后翻开的下一张牌，就吞噬了所有留守的玩家")
EXTEND_ACHIEVEMENT(破釜沉舟, "在探险途中遇见三种不同的怪物，并取得全场最高金币")
EXTEND_ACHIEVEMENT(与狼共舞, "怪物突袭生效后，在路上再分得 30 枚及以上金币并安全撤离")
EXTEND_ACHIEVEMENT(深不可测, "已经翻开 25 张及以上卡牌时安全撤离")
EXTEND_ACHIEVEMENT(急流勇退, "在第一个选择回合就撤离，并取得全场最高金币")
EXTEND_ACHIEVEMENT(见多识广, "在一局中见证全部 8 张奇遇，并安全撤离")
