GAME_OPTION("每回合最长时间x秒", 局时, (ArithChecker<uint32_t>(10, 3600, "局时（秒）")), 120)
GAME_OPTION("随机种子", 种子, (AnyArg("种子", "我是随便输入的一个字符串")), "")
GAME_OPTION("最大回合数", 回合数, (ArithChecker<uint32_t>(10, 100, "回合数")), 40)
GAME_OPTION("当有玩家达到多少积分时，游戏宣告结束", 胜利分数, (ArithChecker<uint32_t>(2, 20, "积分")), 10)
GAME_OPTION("卡片颜色种类数量", 颜色, (ArithChecker<uint32_t>(1, 6, "数量")), 6)
GAME_OPTION("卡片点数种类数量", 点数, (ArithChecker<uint32_t>(1, 6, "数量")), 6)
GAME_OPTION("相同卡片的数量", 副数, (ArithChecker<uint32_t>(1, 10, "数量")), 5)
