EXTEND_ACHIEVEMENT(平步青云, "在默认规则下，单个回合内将一整列从起点推进至顶端并夺得")
EXTEND_ACHIEVEMENT(一气呵成, "在同一回合结束时一次夺得 2 列")
EXTEND_ACHIEVEMENT(三足鼎立, "在同一回合结束时夺得 3 列及以上")
EXTEND_ACHIEVEMENT(稳扎稳打, "整局游戏从未爆掉，并获得游戏胜利")
EXTEND_ACHIEVEMENT(一掷乾坤, "在一次掷骰中掷出四颗同点骰子，且该次未爆掉")
EXTEND_ACHIEVEMENT(贪得无厌, "获胜回合中额外夺得至少 1 列，使总夺得列数超过取胜所需")
EXTEND_ACHIEVEMENT(通吃两极, "同时夺得第 2 列与第 12 列")
EXTEND_ACHIEVEMENT(独占鳌头, "获得游戏胜利，且全程没有任何对手夺得过任何一列")
EXTEND_ACHIEVEMENT(欲罢不能, "在单个回合内投掷骰子达到 20 次且未爆掉")
EXTEND_ACHIEVEMENT(一飞冲天, "在单个回合内将三列各自从起点推进至顶端并夺得")
