// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v7.34.1
// source: command_args.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoidArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidArg) Reset() {
	*x = VoidArg{}
	mi := &file_command_args_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidArg) ProtoMessage() {}

func (x *VoidArg) ProtoReflect() protoreflect.Message {
	mi := &file_command_args_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidArg.ProtoReflect.Descriptor instead.
func (*VoidArg) Descriptor() ([]byte, []int) {
	return file_command_args_proto_rawDescGZIP(), []int{0}
}

func (x *VoidArg) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type BoolArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrueStr       string                 `protobuf:"bytes,1,opt,name=true_str,json=trueStr,proto3" json:"true_str,omitempty"`
	FalseStr      string                 `protobuf:"bytes,2,opt,name=false_str,json=falseStr,proto3" json:"false_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolArg) Reset() {
	*x = BoolArg{}
	mi := &file_command_args_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolArg) ProtoMessage() {}

func (x *BoolArg) ProtoReflect() protoreflect.Message {
	mi := &file_command_args_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolArg.ProtoReflect.Descriptor instead.
func (*BoolArg) Descriptor() ([]byte, []int) {
	return file_command_args_proto_rawDescGZIP(), []int{1}
}

func (x *BoolArg) GetTrueStr() string {
	if x != nil {
		return x.TrueStr
	}
	return ""
}

func (x *BoolArg) GetFalseStr() string {
	if x != nil {
		return x.FalseStr
	}
	return ""
}

type AlternativesArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []string               `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlternativesArg) Reset() {
	*x = AlternativesArg{}
	mi := &file_command_args_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlternativesArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlternativesArg) ProtoMessage() {}

func (x *AlternativesArg) ProtoReflect() protoreflect.Message {
	mi := &file_command_args_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlternativesArg.ProtoReflect.Descriptor instead.
func (*AlternativesArg) Descriptor() ([]byte, []int) {
	return file_command_args_proto_rawDescGZIP(), []int{2}
}

func (x *AlternativesArg) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type IntegerArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int64                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int64                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Meaning       string                 `protobuf:"bytes,3,opt,name=meaning,proto3" json:"meaning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegerArg) Reset() {
	*x = IntegerArg{}
	mi := &file_command_args_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegerArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegerArg) ProtoMessage() {}

func (x *IntegerArg) ProtoReflect() protoreflect.Message {
	mi := &file_command_args_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegerArg.ProtoReflect.Descriptor instead.
func (*IntegerArg) Descriptor() ([]byte, []int) {
	return file_command_args_proto_rawDescGZIP(), []int{3}
}

func (x *IntegerArg) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *IntegerArg) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *IntegerArg) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

type TextArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meaning       string                 `protobuf:"bytes,1,opt,name=meaning,proto3" json:"meaning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextArg) Reset() {
	*x = TextArg{}
	mi := &file_command_args_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextArg) ProtoMessage() {}

func (x *TextArg) ProtoReflect() protoreflect.Message {
	mi := &file_command_args_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextArg.ProtoReflect.Descriptor instead.
func (*TextArg) Descriptor() ([]byte, []int) {
	return file_command_args_proto_rawDescGZIP(), []int{4}
}

func (x *TextArg) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

type OptionalArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inner         *ArgDef                `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalArg) Reset() {
	*x = OptionalArg{}
	mi := &file_command_args_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalArg) ProtoMessage() {}

func (x *OptionalArg) ProtoReflect() protoreflect.Message {
	mi := &file_command_args_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalArg.ProtoReflect.Descriptor instead.
func (*OptionalArg) Descriptor() ([]byte, []int) {
	return file_command_args_proto_rawDescGZIP(), []int{5}
}

func (x *OptionalArg) GetInner() *ArgDef {
	if x != nil {
		return x.Inner
	}
	return nil
}

type RepeatableArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inner         *ArgDef                `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatableArg) Reset() {
	*x = RepeatableArg{}
	mi := &file_command_args_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatableArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatableArg) ProtoMessage() {}

func (x *RepeatableArg) ProtoReflect() protoreflect.Message {
	mi := &file_command_args_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatableArg.ProtoReflect.Descriptor instead.
func (*RepeatableArg) Descriptor() ([]byte, []int) {
	return file_command_args_proto_rawDescGZIP(), []int{6}
}

func (x *RepeatableArg) GetInner() *ArgDef {
	if x != nil {
		return x.Inner
	}
	return nil
}

type ArgDef struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	FormatInfo string                 `protobuf:"bytes,1,opt,name=format_info,json=formatInfo,proto3" json:"format_info,omitempty"`
	Example    string                 `protobuf:"bytes,2,opt,name=example,proto3" json:"example,omitempty"`
	// Types that are valid to be assigned to Arg:
	//
	//	*ArgDef_VoidArg
	//	*ArgDef_BoolArg
	//	*ArgDef_AlternativesArg
	//	*ArgDef_IntegerArg
	//	*ArgDef_TextArg
	//	*ArgDef_OptionalArg
	//	*ArgDef_RepeatableArg
	Arg           isArgDef_Arg `protobuf_oneof:"arg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArgDef) Reset() {
	*x = ArgDef{}
	mi := &file_command_args_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArgDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgDef) ProtoMessage() {}

func (x *ArgDef) ProtoReflect() protoreflect.Message {
	mi := &file_command_args_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgDef.ProtoReflect.Descriptor instead.
func (*ArgDef) Descriptor() ([]byte, []int) {
	return file_command_args_proto_rawDescGZIP(), []int{7}
}

func (x *ArgDef) GetFormatInfo() string {
	if x != nil {
		return x.FormatInfo
	}
	return ""
}

func (x *ArgDef) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *ArgDef) GetArg() isArgDef_Arg {
	if x != nil {
		return x.Arg
	}
	return nil
}

func (x *ArgDef) GetVoidArg() *VoidArg {
	if x != nil {
		if x, ok := x.Arg.(*ArgDef_VoidArg); ok {
			return x.VoidArg
		}
	}
	return nil
}

func (x *ArgDef) GetBoolArg() *BoolArg {
	if x != nil {
		if x, ok := x.Arg.(*ArgDef_BoolArg); ok {
			return x.BoolArg
		}
	}
	return nil
}

func (x *ArgDef) GetAlternativesArg() *AlternativesArg {
	if x != nil {
		if x, ok := x.Arg.(*ArgDef_AlternativesArg); ok {
			return x.AlternativesArg
		}
	}
	return nil
}

func (x *ArgDef) GetIntegerArg() *IntegerArg {
	if x != nil {
		if x, ok := x.Arg.(*ArgDef_IntegerArg); ok {
			return x.IntegerArg
		}
	}
	return nil
}

func (x *ArgDef) GetTextArg() *TextArg {
	if x != nil {
		if x, ok := x.Arg.(*ArgDef_TextArg); ok {
			return x.TextArg
		}
	}
	return nil
}

func (x *ArgDef) GetOptionalArg() *OptionalArg {
	if x != nil {
		if x, ok := x.Arg.(*ArgDef_OptionalArg); ok {
			return x.OptionalArg
		}
	}
	return nil
}

func (x *ArgDef) GetRepeatableArg() *RepeatableArg {
	if x != nil {
		if x, ok := x.Arg.(*ArgDef_RepeatableArg); ok {
			return x.RepeatableArg
		}
	}
	return nil
}

type isArgDef_Arg interface {
	isArgDef_Arg()
}

type ArgDef_VoidArg struct {
	VoidArg *VoidArg `protobuf:"bytes,3,opt,name=void_arg,json=voidArg,proto3,oneof"`
}

type ArgDef_BoolArg struct {
	BoolArg *BoolArg `protobuf:"bytes,4,opt,name=bool_arg,json=boolArg,proto3,oneof"`
}

type ArgDef_AlternativesArg struct {
	AlternativesArg *AlternativesArg `protobuf:"bytes,5,opt,name=alternatives_arg,json=alternativesArg,proto3,oneof"`
}

type ArgDef_IntegerArg struct {
	IntegerArg *IntegerArg `protobuf:"bytes,6,opt,name=integer_arg,json=integerArg,proto3,oneof"`
}

type ArgDef_TextArg struct {
	TextArg *TextArg `protobuf:"bytes,7,opt,name=text_arg,json=textArg,proto3,oneof"`
}

type ArgDef_OptionalArg struct {
	OptionalArg *OptionalArg `protobuf:"bytes,8,opt,name=optional_arg,json=optionalArg,proto3,oneof"`
}

type ArgDef_RepeatableArg struct {
	RepeatableArg *RepeatableArg `protobuf:"bytes,9,opt,name=repeatable_arg,json=repeatableArg,proto3,oneof"`
}

func (*ArgDef_VoidArg) isArgDef_Arg() {}

func (*ArgDef_BoolArg) isArgDef_Arg() {}

func (*ArgDef_AlternativesArg) isArgDef_Arg() {}

func (*ArgDef_IntegerArg) isArgDef_Arg() {}

func (*ArgDef_TextArg) isArgDef_Arg() {}

func (*ArgDef_OptionalArg) isArgDef_Arg() {}

func (*ArgDef_RepeatableArg) isArgDef_Arg() {}

type CommandDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Args          []*ArgDef              `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	IsVisible     bool                   `protobuf:"varint,3,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDef) Reset() {
	*x = CommandDef{}
	mi := &file_command_args_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDef) ProtoMessage() {}

func (x *CommandDef) ProtoReflect() protoreflect.Message {
	mi := &file_command_args_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDef.ProtoReflect.Descriptor instead.
func (*CommandDef) Descriptor() ([]byte, []int) {
	return file_command_args_proto_rawDescGZIP(), []int{8}
}

func (x *CommandDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandDef) GetArgs() []*ArgDef {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandDef) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

var File_command_args_proto protoreflect.FileDescriptor

var file_command_args_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x22, 0x23, 0x0a, 0x07,
	0x56, 0x6f, 0x69, 0x64, 0x41, 0x72, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x41, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6c, 0x41, 0x72, 0x67, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x72, 0x75, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x72, 0x75, 0x65, 0x53, 0x74, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x61, 0x6c, 0x73, 0x65,
	0x5f, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x61, 0x6c, 0x73,
	0x65, 0x53, 0x74, 0x72, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74,
	0x69, 0x76, 0x65, 0x73, 0x41, 0x72, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x4a, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x41, 0x72, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x6d, 0x61, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x23, 0x0a,
	0x07, 0x54, 0x65, 0x78, 0x74, 0x41, 0x72, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x61, 0x6e,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x61, 0x6e, 0x69,
	0x6e, 0x67, 0x22, 0x33, 0x0a, 0x0b, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x41, 0x72,
	0x67, 0x12, 0x24, 0x0a, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x41, 0x72, 0x67, 0x44, 0x65, 0x66,
	0x52, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x35, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x12, 0x24, 0x0a, 0x05, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74,
	0x2e, 0x41, 0x72, 0x67, 0x44, 0x65, 0x66, 0x52, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0xcb,
	0x03, 0x0a, 0x06, 0x41, 0x72, 0x67, 0x44, 0x65, 0x66, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x76, 0x6f, 0x69, 0x64, 0x5f, 0x61, 0x72, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x41, 0x72, 0x67, 0x48, 0x00, 0x52, 0x07, 0x76, 0x6f, 0x69, 0x64, 0x41,
	0x72, 0x67, 0x12, 0x2c, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x61, 0x72, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x42, 0x6f,
	0x6f, 0x6c, 0x41, 0x72, 0x67, 0x48, 0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x41, 0x72, 0x67,
	0x12, 0x44, 0x0a, 0x10, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73,
	0x5f, 0x61, 0x72, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x67, 0x74,
	0x62, 0x6f, 0x74, 0x2e, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73,
	0x41, 0x72, 0x67, 0x48, 0x00, 0x52, 0x0f, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69,
	0x76, 0x65, 0x73, 0x41, 0x72, 0x67, 0x12, 0x35, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65,
	0x72, 0x5f, 0x61, 0x72, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x67,
	0x74, 0x62, 0x6f, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x41, 0x72, 0x67, 0x48,
	0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x41, 0x72, 0x67, 0x12, 0x2c, 0x0a,
	0x08, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x61, 0x72, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x41, 0x72, 0x67,
	0x48, 0x00, 0x52, 0x07, 0x74, 0x65, 0x78, 0x74, 0x41, 0x72, 0x67, 0x12, 0x38, 0x0a, 0x0c, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x72, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x41, 0x72, 0x67, 0x48, 0x00, 0x52, 0x0b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x41, 0x72, 0x67, 0x12, 0x3e, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x61, 0x72, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x41, 0x72, 0x67, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x41, 0x72, 0x67, 0x42, 0x05, 0x0a, 0x03, 0x61, 0x72, 0x67, 0x22, 0x71, 0x0a, 0x0a,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x44, 0x65, 0x66, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x67, 0x74,
	0x62, 0x6f, 0x74, 0x2e, 0x41, 0x72, 0x67, 0x44, 0x65, 0x66, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x42,
	0x14, 0x5a, 0x12, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_command_args_proto_rawDescOnce sync.Once
	file_command_args_proto_rawDescData = file_command_args_proto_rawDesc
)

func file_command_args_proto_rawDescGZIP() []byte {
	file_command_args_proto_rawDescOnce.Do(func() {
		file_command_args_proto_rawDescData = protoimpl.X.CompressGZIP(file_command_args_proto_rawDescData)
	})
	return file_command_args_proto_rawDescData
}

var file_command_args_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_command_args_proto_goTypes = []any{
	(*VoidArg)(nil),         // 0: lgtbot.VoidArg
	(*BoolArg)(nil),         // 1: lgtbot.BoolArg
	(*AlternativesArg)(nil), // 2: lgtbot.AlternativesArg
	(*IntegerArg)(nil),      // 3: lgtbot.IntegerArg
	(*TextArg)(nil),         // 4: lgtbot.TextArg
	(*OptionalArg)(nil),     // 5: lgtbot.OptionalArg
	(*RepeatableArg)(nil),   // 6: lgtbot.RepeatableArg
	(*ArgDef)(nil),          // 7: lgtbot.ArgDef
	(*CommandDef)(nil),      // 8: lgtbot.CommandDef
}
var file_command_args_proto_depIdxs = []int32{
	7,  // 0: lgtbot.OptionalArg.inner:type_name -> lgtbot.ArgDef
	7,  // 1: lgtbot.RepeatableArg.inner:type_name -> lgtbot.ArgDef
	0,  // 2: lgtbot.ArgDef.void_arg:type_name -> lgtbot.VoidArg
	1,  // 3: lgtbot.ArgDef.bool_arg:type_name -> lgtbot.BoolArg
	2,  // 4: lgtbot.ArgDef.alternatives_arg:type_name -> lgtbot.AlternativesArg
	3,  // 5: lgtbot.ArgDef.integer_arg:type_name -> lgtbot.IntegerArg
	4,  // 6: lgtbot.ArgDef.text_arg:type_name -> lgtbot.TextArg
	5,  // 7: lgtbot.ArgDef.optional_arg:type_name -> lgtbot.OptionalArg
	6,  // 8: lgtbot.ArgDef.repeatable_arg:type_name -> lgtbot.RepeatableArg
	7,  // 9: lgtbot.CommandDef.args:type_name -> lgtbot.ArgDef
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_command_args_proto_init() }
func file_command_args_proto_init() {
	if File_command_args_proto != nil {
		return
	}
	file_command_args_proto_msgTypes[7].OneofWrappers = []any{
		(*ArgDef_VoidArg)(nil),
		(*ArgDef_BoolArg)(nil),
		(*ArgDef_AlternativesArg)(nil),
		(*ArgDef_IntegerArg)(nil),
		(*ArgDef_TextArg)(nil),
		(*ArgDef_OptionalArg)(nil),
		(*ArgDef_RepeatableArg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_command_args_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_command_args_proto_goTypes,
		DependencyIndexes: file_command_args_proto_depIdxs,
		MessageInfos:      file_command_args_proto_msgTypes,
	}.Build()
	File_command_args_proto = out.File
	file_command_args_proto_rawDesc = nil
	file_command_args_proto_goTypes = nil
	file_command_args_proto_depIdxs = nil
}
