// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: lgtbot_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LGTBotService_HandlePrivateRequest_FullMethodName   = "/lgtbot.LGTBotService/HandlePrivateRequest"
	LGTBotService_Subscribe_FullMethodName              = "/lgtbot.LGTBotService/Subscribe"
	LGTBotService_GetCommands_FullMethodName            = "/lgtbot.LGTBotService/GetCommands"
	LGTBotService_GetUserInfo_FullMethodName            = "/lgtbot.LGTBotService/GetUserInfo"
	LGTBotService_GetMatchHistory_FullMethodName        = "/lgtbot.LGTBotService/GetMatchHistory"
	LGTBotService_UpdateUserInfo_FullMethodName         = "/lgtbot.LGTBotService/UpdateUserInfo"
	LGTBotService_RecordChatMessage_FullMethodName      = "/lgtbot.LGTBotService/RecordChatMessage"
	LGTBotService_GetGameList_FullMethodName            = "/lgtbot.LGTBotService/GetGameList"
	LGTBotService_StartGame_FullMethodName              = "/lgtbot.LGTBotService/StartGame"
	LGTBotService_WebListGameMatches_FullMethodName     = "/lgtbot.LGTBotService/WebListGameMatches"
	LGTBotService_WebGetGameRule_FullMethodName         = "/lgtbot.LGTBotService/WebGetGameRule"
	LGTBotService_WebGetGameAchievements_FullMethodName = "/lgtbot.LGTBotService/WebGetGameAchievements"
	LGTBotService_WebGetGameRankings_FullMethodName     = "/lgtbot.LGTBotService/WebGetGameRankings"
	LGTBotService_WebUserProfile_FullMethodName         = "/lgtbot.LGTBotService/WebUserProfile"
)

// LGTBotServiceClient is the client API for LGTBotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LGTBotServiceClient interface {
	HandlePrivateRequest(ctx context.Context, in *PrivateRequest, opts ...grpc.CallOption) (*PrivateResponse, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PushEvent], error)
	GetCommands(ctx context.Context, in *GetCommandsRequest, opts ...grpc.CallOption) (*GetCommandsResponse, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	GetMatchHistory(ctx context.Context, in *GetMatchHistoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error)
	UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error)
	RecordChatMessage(ctx context.Context, in *RecordChatMessageRequest, opts ...grpc.CallOption) (*RecordChatMessageResponse, error)
	GetGameList(ctx context.Context, in *GetGameListRequest, opts ...grpc.CallOption) (*GetGameListResponse, error)
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error)
	WebListGameMatches(ctx context.Context, in *WebListGameMatchesRequest, opts ...grpc.CallOption) (*WebListGameMatchesResponse, error)
	WebGetGameRule(ctx context.Context, in *WebGetGameRuleRequest, opts ...grpc.CallOption) (*WebGetGameRuleResponse, error)
	WebGetGameAchievements(ctx context.Context, in *WebGetGameAchievementsRequest, opts ...grpc.CallOption) (*WebGetGameAchievementsResponse, error)
	WebGetGameRankings(ctx context.Context, in *WebGetGameRankingsRequest, opts ...grpc.CallOption) (*WebGetGameRankingsResponse, error)
	WebUserProfile(ctx context.Context, in *WebUserProfileRequest, opts ...grpc.CallOption) (*WebUserProfileResponse, error)
}

type lGTBotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLGTBotServiceClient(cc grpc.ClientConnInterface) LGTBotServiceClient {
	return &lGTBotServiceClient{cc}
}

func (c *lGTBotServiceClient) HandlePrivateRequest(ctx context.Context, in *PrivateRequest, opts ...grpc.CallOption) (*PrivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrivateResponse)
	err := c.cc.Invoke(ctx, LGTBotService_HandlePrivateRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lGTBotServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PushEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LGTBotService_ServiceDesc.Streams[0], LGTBotService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, PushEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LGTBotService_SubscribeClient = grpc.ServerStreamingClient[PushEvent]

func (c *lGTBotServiceClient) GetCommands(ctx context.Context, in *GetCommandsRequest, opts ...grpc.CallOption) (*GetCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommandsResponse)
	err := c.cc.Invoke(ctx, LGTBotService_GetCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lGTBotServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, LGTBotService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lGTBotServiceClient) GetMatchHistory(ctx context.Context, in *GetMatchHistoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LGTBotService_ServiceDesc.Streams[1], LGTBotService_GetMatchHistory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetMatchHistoryRequest, Message]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LGTBotService_GetMatchHistoryClient = grpc.ServerStreamingClient[Message]

func (c *lGTBotServiceClient) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserInfoResponse)
	err := c.cc.Invoke(ctx, LGTBotService_UpdateUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lGTBotServiceClient) RecordChatMessage(ctx context.Context, in *RecordChatMessageRequest, opts ...grpc.CallOption) (*RecordChatMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordChatMessageResponse)
	err := c.cc.Invoke(ctx, LGTBotService_RecordChatMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lGTBotServiceClient) GetGameList(ctx context.Context, in *GetGameListRequest, opts ...grpc.CallOption) (*GetGameListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameListResponse)
	err := c.cc.Invoke(ctx, LGTBotService_GetGameList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lGTBotServiceClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, LGTBotService_StartGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lGTBotServiceClient) WebListGameMatches(ctx context.Context, in *WebListGameMatchesRequest, opts ...grpc.CallOption) (*WebListGameMatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebListGameMatchesResponse)
	err := c.cc.Invoke(ctx, LGTBotService_WebListGameMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lGTBotServiceClient) WebGetGameRule(ctx context.Context, in *WebGetGameRuleRequest, opts ...grpc.CallOption) (*WebGetGameRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebGetGameRuleResponse)
	err := c.cc.Invoke(ctx, LGTBotService_WebGetGameRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lGTBotServiceClient) WebGetGameAchievements(ctx context.Context, in *WebGetGameAchievementsRequest, opts ...grpc.CallOption) (*WebGetGameAchievementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebGetGameAchievementsResponse)
	err := c.cc.Invoke(ctx, LGTBotService_WebGetGameAchievements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lGTBotServiceClient) WebGetGameRankings(ctx context.Context, in *WebGetGameRankingsRequest, opts ...grpc.CallOption) (*WebGetGameRankingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebGetGameRankingsResponse)
	err := c.cc.Invoke(ctx, LGTBotService_WebGetGameRankings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lGTBotServiceClient) WebUserProfile(ctx context.Context, in *WebUserProfileRequest, opts ...grpc.CallOption) (*WebUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebUserProfileResponse)
	err := c.cc.Invoke(ctx, LGTBotService_WebUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LGTBotServiceServer is the server API for LGTBotService service.
// All implementations must embed UnimplementedLGTBotServiceServer
// for forward compatibility.
type LGTBotServiceServer interface {
	HandlePrivateRequest(context.Context, *PrivateRequest) (*PrivateResponse, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[PushEvent]) error
	GetCommands(context.Context, *GetCommandsRequest) (*GetCommandsResponse, error)
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	GetMatchHistory(*GetMatchHistoryRequest, grpc.ServerStreamingServer[Message]) error
	UpdateUserInfo(context.Context, *UpdateUserInfoRequest) (*UpdateUserInfoResponse, error)
	RecordChatMessage(context.Context, *RecordChatMessageRequest) (*RecordChatMessageResponse, error)
	GetGameList(context.Context, *GetGameListRequest) (*GetGameListResponse, error)
	StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error)
	WebListGameMatches(context.Context, *WebListGameMatchesRequest) (*WebListGameMatchesResponse, error)
	WebGetGameRule(context.Context, *WebGetGameRuleRequest) (*WebGetGameRuleResponse, error)
	WebGetGameAchievements(context.Context, *WebGetGameAchievementsRequest) (*WebGetGameAchievementsResponse, error)
	WebGetGameRankings(context.Context, *WebGetGameRankingsRequest) (*WebGetGameRankingsResponse, error)
	WebUserProfile(context.Context, *WebUserProfileRequest) (*WebUserProfileResponse, error)
	mustEmbedUnimplementedLGTBotServiceServer()
}

// UnimplementedLGTBotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLGTBotServiceServer struct{}

func (UnimplementedLGTBotServiceServer) HandlePrivateRequest(context.Context, *PrivateRequest) (*PrivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandlePrivateRequest not implemented")
}
func (UnimplementedLGTBotServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[PushEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedLGTBotServiceServer) GetCommands(context.Context, *GetCommandsRequest) (*GetCommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommands not implemented")
}
func (UnimplementedLGTBotServiceServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedLGTBotServiceServer) GetMatchHistory(*GetMatchHistoryRequest, grpc.ServerStreamingServer[Message]) error {
	return status.Error(codes.Unimplemented, "method GetMatchHistory not implemented")
}
func (UnimplementedLGTBotServiceServer) UpdateUserInfo(context.Context, *UpdateUserInfoRequest) (*UpdateUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserInfo not implemented")
}
func (UnimplementedLGTBotServiceServer) RecordChatMessage(context.Context, *RecordChatMessageRequest) (*RecordChatMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordChatMessage not implemented")
}
func (UnimplementedLGTBotServiceServer) GetGameList(context.Context, *GetGameListRequest) (*GetGameListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameList not implemented")
}
func (UnimplementedLGTBotServiceServer) StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedLGTBotServiceServer) WebListGameMatches(context.Context, *WebListGameMatchesRequest) (*WebListGameMatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WebListGameMatches not implemented")
}
func (UnimplementedLGTBotServiceServer) WebGetGameRule(context.Context, *WebGetGameRuleRequest) (*WebGetGameRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WebGetGameRule not implemented")
}
func (UnimplementedLGTBotServiceServer) WebGetGameAchievements(context.Context, *WebGetGameAchievementsRequest) (*WebGetGameAchievementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WebGetGameAchievements not implemented")
}
func (UnimplementedLGTBotServiceServer) WebGetGameRankings(context.Context, *WebGetGameRankingsRequest) (*WebGetGameRankingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WebGetGameRankings not implemented")
}
func (UnimplementedLGTBotServiceServer) WebUserProfile(context.Context, *WebUserProfileRequest) (*WebUserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WebUserProfile not implemented")
}
func (UnimplementedLGTBotServiceServer) mustEmbedUnimplementedLGTBotServiceServer() {}
func (UnimplementedLGTBotServiceServer) testEmbeddedByValue()                       {}

// UnsafeLGTBotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LGTBotServiceServer will
// result in compilation errors.
type UnsafeLGTBotServiceServer interface {
	mustEmbedUnimplementedLGTBotServiceServer()
}

func RegisterLGTBotServiceServer(s grpc.ServiceRegistrar, srv LGTBotServiceServer) {
	// If the following call panics, it indicates UnimplementedLGTBotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LGTBotService_ServiceDesc, srv)
}

func _LGTBotService_HandlePrivateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).HandlePrivateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_HandlePrivateRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).HandlePrivateRequest(ctx, req.(*PrivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LGTBotService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LGTBotServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, PushEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LGTBotService_SubscribeServer = grpc.ServerStreamingServer[PushEvent]

func _LGTBotService_GetCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).GetCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_GetCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).GetCommands(ctx, req.(*GetCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LGTBotService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LGTBotService_GetMatchHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMatchHistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LGTBotServiceServer).GetMatchHistory(m, &grpc.GenericServerStream[GetMatchHistoryRequest, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LGTBotService_GetMatchHistoryServer = grpc.ServerStreamingServer[Message]

func _LGTBotService_UpdateUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).UpdateUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_UpdateUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).UpdateUserInfo(ctx, req.(*UpdateUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LGTBotService_RecordChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordChatMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).RecordChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_RecordChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).RecordChatMessage(ctx, req.(*RecordChatMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LGTBotService_GetGameList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).GetGameList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_GetGameList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).GetGameList(ctx, req.(*GetGameListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LGTBotService_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_StartGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LGTBotService_WebListGameMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebListGameMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).WebListGameMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_WebListGameMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).WebListGameMatches(ctx, req.(*WebListGameMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LGTBotService_WebGetGameRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebGetGameRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).WebGetGameRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_WebGetGameRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).WebGetGameRule(ctx, req.(*WebGetGameRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LGTBotService_WebGetGameAchievements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebGetGameAchievementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).WebGetGameAchievements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_WebGetGameAchievements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).WebGetGameAchievements(ctx, req.(*WebGetGameAchievementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LGTBotService_WebGetGameRankings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebGetGameRankingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).WebGetGameRankings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_WebGetGameRankings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).WebGetGameRankings(ctx, req.(*WebGetGameRankingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LGTBotService_WebUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LGTBotServiceServer).WebUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LGTBotService_WebUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LGTBotServiceServer).WebUserProfile(ctx, req.(*WebUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LGTBotService_ServiceDesc is the grpc.ServiceDesc for LGTBotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LGTBotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lgtbot.LGTBotService",
	HandlerType: (*LGTBotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandlePrivateRequest",
			Handler:    _LGTBotService_HandlePrivateRequest_Handler,
		},
		{
			MethodName: "GetCommands",
			Handler:    _LGTBotService_GetCommands_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _LGTBotService_GetUserInfo_Handler,
		},
		{
			MethodName: "UpdateUserInfo",
			Handler:    _LGTBotService_UpdateUserInfo_Handler,
		},
		{
			MethodName: "RecordChatMessage",
			Handler:    _LGTBotService_RecordChatMessage_Handler,
		},
		{
			MethodName: "GetGameList",
			Handler:    _LGTBotService_GetGameList_Handler,
		},
		{
			MethodName: "StartGame",
			Handler:    _LGTBotService_StartGame_Handler,
		},
		{
			MethodName: "WebListGameMatches",
			Handler:    _LGTBotService_WebListGameMatches_Handler,
		},
		{
			MethodName: "WebGetGameRule",
			Handler:    _LGTBotService_WebGetGameRule_Handler,
		},
		{
			MethodName: "WebGetGameAchievements",
			Handler:    _LGTBotService_WebGetGameAchievements_Handler,
		},
		{
			MethodName: "WebGetGameRankings",
			Handler:    _LGTBotService_WebGetGameRankings_Handler,
		},
		{
			MethodName: "WebUserProfile",
			Handler:    _LGTBotService_WebUserProfile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _LGTBotService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetMatchHistory",
			Handler:       _LGTBotService_GetMatchHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lgtbot_service.proto",
}
