// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v7.34.1
// source: lgtbot_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ===== Common =====
type ImageMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	DeleteAfterSend bool                   `protobuf:"varint,2,opt,name=delete_after_send,json=deleteAfterSend,proto3" json:"delete_after_send,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImageMsg) Reset() {
	*x = ImageMsg{}
	mi := &file_lgtbot_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMsg) ProtoMessage() {}

func (x *ImageMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMsg.ProtoReflect.Descriptor instead.
func (*ImageMsg) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{0}
}

func (x *ImageMsg) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageMsg) GetDeleteAfterSend() bool {
	if x != nil {
		return x.DeleteAfterSend
	}
	return false
}

type MsgItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*MsgItem_Text
	//	*MsgItem_Image
	//	*MsgItem_AtPlatformUserId
	//	*MsgItem_Html
	Msg           isMsgItem_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgItem) Reset() {
	*x = MsgItem{}
	mi := &file_lgtbot_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgItem) ProtoMessage() {}

func (x *MsgItem) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgItem.ProtoReflect.Descriptor instead.
func (*MsgItem) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{1}
}

func (x *MsgItem) GetMsg() isMsgItem_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MsgItem) GetText() string {
	if x != nil {
		if x, ok := x.Msg.(*MsgItem_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *MsgItem) GetImage() *ImageMsg {
	if x != nil {
		if x, ok := x.Msg.(*MsgItem_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *MsgItem) GetAtPlatformUserId() string {
	if x != nil {
		if x, ok := x.Msg.(*MsgItem_AtPlatformUserId); ok {
			return x.AtPlatformUserId
		}
	}
	return ""
}

func (x *MsgItem) GetHtml() string {
	if x != nil {
		if x, ok := x.Msg.(*MsgItem_Html); ok {
			return x.Html
		}
	}
	return ""
}

type isMsgItem_Msg interface {
	isMsgItem_Msg()
}

type MsgItem_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type MsgItem_Image struct {
	Image *ImageMsg `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type MsgItem_AtPlatformUserId struct {
	AtPlatformUserId string `protobuf:"bytes,3,opt,name=at_platform_user_id,json=atPlatformUserId,proto3,oneof"`
}

type MsgItem_Html struct {
	Html string `protobuf:"bytes,4,opt,name=html,proto3,oneof"`
}

func (*MsgItem_Text) isMsgItem_Msg() {}

func (*MsgItem_Image) isMsgItem_Msg() {}

func (*MsgItem_AtPlatformUserId) isMsgItem_Msg() {}

func (*MsgItem_Html) isMsgItem_Msg() {}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MsgItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_lgtbot_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetItems() []*MsgItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// ===== HandlePrivateRequest =====
type PrivateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	Text           string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrivateRequest) Reset() {
	*x = PrivateRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateRequest) ProtoMessage() {}

func (x *PrivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateRequest.ProtoReflect.Descriptor instead.
func (*PrivateRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{3}
}

func (x *PrivateRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PrivateRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

func (x *PrivateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PrivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateResponse) Reset() {
	*x = PrivateResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateResponse) ProtoMessage() {}

func (x *PrivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateResponse.ProtoReflect.Descriptor instead.
func (*PrivateResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{4}
}

func (x *PrivateResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *PrivateResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// ===== Subscribe =====
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type MatchStartEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlatformGroupId string                 `protobuf:"bytes,1,opt,name=platform_group_id,json=platformGroupId,proto3" json:"platform_group_id,omitempty"`
	PlatformUserIds []string               `protobuf:"bytes,2,rep,name=platform_user_ids,json=platformUserIds,proto3" json:"platform_user_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchStartEvent) Reset() {
	*x = MatchStartEvent{}
	mi := &file_lgtbot_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartEvent) ProtoMessage() {}

func (x *MatchStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartEvent.ProtoReflect.Descriptor instead.
func (*MatchStartEvent) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{6}
}

func (x *MatchStartEvent) GetPlatformGroupId() string {
	if x != nil {
		return x.PlatformGroupId
	}
	return ""
}

func (x *MatchStartEvent) GetPlatformUserIds() []string {
	if x != nil {
		return x.PlatformUserIds
	}
	return nil
}

type MatchEndEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlatformGroupId string                 `protobuf:"bytes,1,opt,name=platform_group_id,json=platformGroupId,proto3" json:"platform_group_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchEndEvent) Reset() {
	*x = MatchEndEvent{}
	mi := &file_lgtbot_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEndEvent) ProtoMessage() {}

func (x *MatchEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEndEvent.ProtoReflect.Descriptor instead.
func (*MatchEndEvent) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{7}
}

func (x *MatchEndEvent) GetPlatformGroupId() string {
	if x != nil {
		return x.PlatformGroupId
	}
	return ""
}

type CommandsUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CommandDef          `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandsUpdateEvent) Reset() {
	*x = CommandsUpdateEvent{}
	mi := &file_lgtbot_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandsUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandsUpdateEvent) ProtoMessage() {}

func (x *CommandsUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandsUpdateEvent.ProtoReflect.Descriptor instead.
func (*CommandsUpdateEvent) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{8}
}

func (x *CommandsUpdateEvent) GetCommands() []*CommandDef {
	if x != nil {
		return x.Commands
	}
	return nil
}

type PushEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventSign uint64                 `protobuf:"varint,1,opt,name=event_sign,json=eventSign,proto3" json:"event_sign,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*PushEvent_PlatformUserId
	//	*PushEvent_PlatformGroupId
	Target isPushEvent_Target `protobuf_oneof:"target"`
	// Types that are valid to be assigned to Event:
	//
	//	*PushEvent_Message
	//	*PushEvent_MatchStart
	//	*PushEvent_MatchEnd
	//	*PushEvent_CommandsUpdate
	Event         isPushEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEvent) Reset() {
	*x = PushEvent{}
	mi := &file_lgtbot_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEvent) ProtoMessage() {}

func (x *PushEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEvent.ProtoReflect.Descriptor instead.
func (*PushEvent) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{9}
}

func (x *PushEvent) GetEventSign() uint64 {
	if x != nil {
		return x.EventSign
	}
	return 0
}

func (x *PushEvent) GetTarget() isPushEvent_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PushEvent) GetPlatformUserId() string {
	if x != nil {
		if x, ok := x.Target.(*PushEvent_PlatformUserId); ok {
			return x.PlatformUserId
		}
	}
	return ""
}

func (x *PushEvent) GetPlatformGroupId() string {
	if x != nil {
		if x, ok := x.Target.(*PushEvent_PlatformGroupId); ok {
			return x.PlatformGroupId
		}
	}
	return ""
}

func (x *PushEvent) GetEvent() isPushEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *PushEvent) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Event.(*PushEvent_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *PushEvent) GetMatchStart() *MatchStartEvent {
	if x != nil {
		if x, ok := x.Event.(*PushEvent_MatchStart); ok {
			return x.MatchStart
		}
	}
	return nil
}

func (x *PushEvent) GetMatchEnd() *MatchEndEvent {
	if x != nil {
		if x, ok := x.Event.(*PushEvent_MatchEnd); ok {
			return x.MatchEnd
		}
	}
	return nil
}

func (x *PushEvent) GetCommandsUpdate() *CommandsUpdateEvent {
	if x != nil {
		if x, ok := x.Event.(*PushEvent_CommandsUpdate); ok {
			return x.CommandsUpdate
		}
	}
	return nil
}

type isPushEvent_Target interface {
	isPushEvent_Target()
}

type PushEvent_PlatformUserId struct {
	PlatformUserId string `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3,oneof"`
}

type PushEvent_PlatformGroupId struct {
	PlatformGroupId string `protobuf:"bytes,3,opt,name=platform_group_id,json=platformGroupId,proto3,oneof"`
}

func (*PushEvent_PlatformUserId) isPushEvent_Target() {}

func (*PushEvent_PlatformGroupId) isPushEvent_Target() {}

type isPushEvent_Event interface {
	isPushEvent_Event()
}

type PushEvent_Message struct {
	Message *Message `protobuf:"bytes,4,opt,name=message,proto3,oneof"`
}

type PushEvent_MatchStart struct {
	MatchStart *MatchStartEvent `protobuf:"bytes,5,opt,name=match_start,json=matchStart,proto3,oneof"`
}

type PushEvent_MatchEnd struct {
	MatchEnd *MatchEndEvent `protobuf:"bytes,6,opt,name=match_end,json=matchEnd,proto3,oneof"`
}

type PushEvent_CommandsUpdate struct {
	CommandsUpdate *CommandsUpdateEvent `protobuf:"bytes,7,opt,name=commands_update,json=commandsUpdate,proto3,oneof"`
}

func (*PushEvent_Message) isPushEvent_Event() {}

func (*PushEvent_MatchStart) isPushEvent_Event() {}

func (*PushEvent_MatchEnd) isPushEvent_Event() {}

func (*PushEvent_CommandsUpdate) isPushEvent_Event() {}

type GetCommandsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCommandsRequest) Reset() {
	*x = GetCommandsRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandsRequest) ProtoMessage() {}

func (x *GetCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandsRequest.ProtoReflect.Descriptor instead.
func (*GetCommandsRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommandsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetCommandsRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

type GetCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CommandDef          `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandsResponse) Reset() {
	*x = GetCommandsResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandsResponse) ProtoMessage() {}

func (x *GetCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandsResponse.ProtoReflect.Descriptor instead.
func (*GetCommandsResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCommandsResponse) GetCommands() []*CommandDef {
	if x != nil {
		return x.Commands
	}
	return nil
}

type GetUserInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserInfoRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetUserInfoRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserInfoResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetUserInfoResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type GetMatchHistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMatchHistoryRequest) Reset() {
	*x = GetMatchHistoryRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchHistoryRequest) ProtoMessage() {}

func (x *GetMatchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetMatchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetMatchHistoryRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetMatchHistoryRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

type UpdateUserInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarPng      []byte                 `protobuf:"bytes,4,opt,name=avatar_png,json=avatarPng,proto3" json:"avatar_png,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserInfoRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetAvatarPng() []byte {
	if x != nil {
		return x.AvatarPng
	}
	return nil
}

type UpdateUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoResponse) Reset() {
	*x = UpdateUserInfoResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoResponse) ProtoMessage() {}

func (x *UpdateUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{16}
}

type RecordChatMessageRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Platform           string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	FromPlatformUserId string                 `protobuf:"bytes,2,opt,name=from_platform_user_id,json=fromPlatformUserId,proto3" json:"from_platform_user_id,omitempty"`
	Text               string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ToPlatformUserId   string                 `protobuf:"bytes,4,opt,name=to_platform_user_id,json=toPlatformUserId,proto3" json:"to_platform_user_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordChatMessageRequest) Reset() {
	*x = RecordChatMessageRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordChatMessageRequest) ProtoMessage() {}

func (x *RecordChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordChatMessageRequest.ProtoReflect.Descriptor instead.
func (*RecordChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{17}
}

func (x *RecordChatMessageRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RecordChatMessageRequest) GetFromPlatformUserId() string {
	if x != nil {
		return x.FromPlatformUserId
	}
	return ""
}

func (x *RecordChatMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RecordChatMessageRequest) GetToPlatformUserId() string {
	if x != nil {
		return x.ToPlatformUserId
	}
	return ""
}

type RecordChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordChatMessageResponse) Reset() {
	*x = RecordChatMessageResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordChatMessageResponse) ProtoMessage() {}

func (x *RecordChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordChatMessageResponse.ProtoReflect.Descriptor instead.
func (*RecordChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{18}
}

type GetGameListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListRequest) Reset() {
	*x = GetGameListRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListRequest) ProtoMessage() {}

func (x *GetGameListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListRequest.ProtoReflect.Descriptor instead.
func (*GetGameListRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{19}
}

type GameInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Developer     string                 `protobuf:"bytes,2,opt,name=developer,proto3" json:"developer,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MinPlayers    uint32                 `protobuf:"varint,4,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`
	MaxPlayers    uint32                 `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	mi := &file_lgtbot_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{20}
}

func (x *GameInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameInfo) GetDeveloper() string {
	if x != nil {
		return x.Developer
	}
	return ""
}

func (x *GameInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GameInfo) GetMinPlayers() uint32 {
	if x != nil {
		return x.MinPlayers
	}
	return 0
}

func (x *GameInfo) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type GetGameListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*GameInfo            `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListResponse) Reset() {
	*x = GetGameListResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListResponse) ProtoMessage() {}

func (x *GetGameListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListResponse.ProtoReflect.Descriptor instead.
func (*GetGameListResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetGameListResponse) GetGames() []*GameInfo {
	if x != nil {
		return x.Games
	}
	return nil
}

type StartGameRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	GameName       string                 `protobuf:"bytes,3,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	Solo           bool                   `protobuf:"varint,4,opt,name=solo,proto3" json:"solo,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{22}
}

func (x *StartGameRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *StartGameRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

func (x *StartGameRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *StartGameRequest) GetSolo() bool {
	if x != nil {
		return x.Solo
	}
	return false
}

type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{23}
}

func (x *StartGameResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *StartGameResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_lgtbot_service_proto protoreflect.FileDescriptor

var file_lgtbot_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x1a, 0x12,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x48, 0x0a, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x12, 0x2a, 0x0a, 0x11, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x66, 0x74, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x22, 0x97, 0x01, 0x0a,
	0x07, 0x4d, 0x73, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4d, 0x73, 0x67, 0x48,
	0x00, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x61, 0x74, 0x5f, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x10, 0x61, 0x74, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x68, 0x74, 0x6d,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x42,
	0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x30, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x6a, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x45, 0x0a, 0x0f, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x2e, 0x0a, 0x10, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x69, 0x0a, 0x0f, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2a,
	0x0a, 0x11, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x3b, 0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x45,
	0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c,
	0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x44, 0x65, 0x66,
	0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x22, 0xfe, 0x02, 0x0a, 0x09, 0x50,
	0x75, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x01, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a,
	0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x01, 0x52, 0x0a,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x45, 0x6e, 0x64, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x01, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x45, 0x6e, 0x64,
	0x12, 0x46, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x5f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x67, 0x74, 0x62,
	0x6f, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x01, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x28, 0x0a,
	0x10, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e,
	0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x44, 0x65, 0x66, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x22, 0x5a,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x28, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x55, 0x72, 0x6c, 0x22, 0x5e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x5f, 0x70, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x50, 0x6e, 0x67, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0xac, 0x01, 0x0a, 0x18, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x31, 0x0a, 0x15, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x66, 0x72, 0x6f, 0x6d, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x2d, 0x0a, 0x13, 0x74, 0x6f, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x6f,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x1b,
	0x0a, 0x19, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6d, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x22, 0x3d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x67, 0x74,
	0x62, 0x6f, 0x74, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x67, 0x61,
	0x6d, 0x65, 0x73, 0x22, 0x89, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6f, 0x6c, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x6f, 0x6c, 0x6f, 0x22,
	0x47, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x32, 0x9f, 0x05, 0x0a, 0x0d, 0x4c, 0x47, 0x54,
	0x42, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x14, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6c, 0x67, 0x74,
	0x62, 0x6f, 0x74, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x12, 0x18, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6c, 0x67, 0x74,
	0x62, 0x6f, 0x74, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x12,
	0x46, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x1a,
	0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6c, 0x67, 0x74,
	0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x1e, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x30, 0x01, 0x12, 0x4f, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x6c, 0x67,
	0x74, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x68, 0x61,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x46, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1a, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6c, 0x67,
	0x74, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x6c, 0x67, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x6c, 0x67,
	0x74, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lgtbot_service_proto_rawDescOnce sync.Once
	file_lgtbot_service_proto_rawDescData = file_lgtbot_service_proto_rawDesc
)

func file_lgtbot_service_proto_rawDescGZIP() []byte {
	file_lgtbot_service_proto_rawDescOnce.Do(func() {
		file_lgtbot_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_lgtbot_service_proto_rawDescData)
	})
	return file_lgtbot_service_proto_rawDescData
}

var file_lgtbot_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_lgtbot_service_proto_goTypes = []any{
	(*ImageMsg)(nil),                  // 0: lgtbot.ImageMsg
	(*MsgItem)(nil),                   // 1: lgtbot.MsgItem
	(*Message)(nil),                   // 2: lgtbot.Message
	(*PrivateRequest)(nil),            // 3: lgtbot.PrivateRequest
	(*PrivateResponse)(nil),           // 4: lgtbot.PrivateResponse
	(*SubscribeRequest)(nil),          // 5: lgtbot.SubscribeRequest
	(*MatchStartEvent)(nil),           // 6: lgtbot.MatchStartEvent
	(*MatchEndEvent)(nil),             // 7: lgtbot.MatchEndEvent
	(*CommandsUpdateEvent)(nil),       // 8: lgtbot.CommandsUpdateEvent
	(*PushEvent)(nil),                 // 9: lgtbot.PushEvent
	(*GetCommandsRequest)(nil),        // 10: lgtbot.GetCommandsRequest
	(*GetCommandsResponse)(nil),       // 11: lgtbot.GetCommandsResponse
	(*GetUserInfoRequest)(nil),        // 12: lgtbot.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),       // 13: lgtbot.GetUserInfoResponse
	(*GetMatchHistoryRequest)(nil),    // 14: lgtbot.GetMatchHistoryRequest
	(*UpdateUserInfoRequest)(nil),     // 15: lgtbot.UpdateUserInfoRequest
	(*UpdateUserInfoResponse)(nil),    // 16: lgtbot.UpdateUserInfoResponse
	(*RecordChatMessageRequest)(nil),  // 17: lgtbot.RecordChatMessageRequest
	(*RecordChatMessageResponse)(nil), // 18: lgtbot.RecordChatMessageResponse
	(*GetGameListRequest)(nil),        // 19: lgtbot.GetGameListRequest
	(*GameInfo)(nil),                  // 20: lgtbot.GameInfo
	(*GetGameListResponse)(nil),       // 21: lgtbot.GetGameListResponse
	(*StartGameRequest)(nil),          // 22: lgtbot.StartGameRequest
	(*StartGameResponse)(nil),         // 23: lgtbot.StartGameResponse
	(*CommandDef)(nil),                // 24: lgtbot.CommandDef
}
var file_lgtbot_service_proto_depIdxs = []int32{
	0,  // 0: lgtbot.MsgItem.image:type_name -> lgtbot.ImageMsg
	1,  // 1: lgtbot.Message.items:type_name -> lgtbot.MsgItem
	24, // 2: lgtbot.CommandsUpdateEvent.commands:type_name -> lgtbot.CommandDef
	2,  // 3: lgtbot.PushEvent.message:type_name -> lgtbot.Message
	6,  // 4: lgtbot.PushEvent.match_start:type_name -> lgtbot.MatchStartEvent
	7,  // 5: lgtbot.PushEvent.match_end:type_name -> lgtbot.MatchEndEvent
	8,  // 6: lgtbot.PushEvent.commands_update:type_name -> lgtbot.CommandsUpdateEvent
	24, // 7: lgtbot.GetCommandsResponse.commands:type_name -> lgtbot.CommandDef
	20, // 8: lgtbot.GetGameListResponse.games:type_name -> lgtbot.GameInfo
	3,  // 9: lgtbot.LGTBotService.HandlePrivateRequest:input_type -> lgtbot.PrivateRequest
	5,  // 10: lgtbot.LGTBotService.Subscribe:input_type -> lgtbot.SubscribeRequest
	10, // 11: lgtbot.LGTBotService.GetCommands:input_type -> lgtbot.GetCommandsRequest
	12, // 12: lgtbot.LGTBotService.GetUserInfo:input_type -> lgtbot.GetUserInfoRequest
	14, // 13: lgtbot.LGTBotService.GetMatchHistory:input_type -> lgtbot.GetMatchHistoryRequest
	15, // 14: lgtbot.LGTBotService.UpdateUserInfo:input_type -> lgtbot.UpdateUserInfoRequest
	17, // 15: lgtbot.LGTBotService.RecordChatMessage:input_type -> lgtbot.RecordChatMessageRequest
	19, // 16: lgtbot.LGTBotService.GetGameList:input_type -> lgtbot.GetGameListRequest
	22, // 17: lgtbot.LGTBotService.StartGame:input_type -> lgtbot.StartGameRequest
	4,  // 18: lgtbot.LGTBotService.HandlePrivateRequest:output_type -> lgtbot.PrivateResponse
	9,  // 19: lgtbot.LGTBotService.Subscribe:output_type -> lgtbot.PushEvent
	11, // 20: lgtbot.LGTBotService.GetCommands:output_type -> lgtbot.GetCommandsResponse
	13, // 21: lgtbot.LGTBotService.GetUserInfo:output_type -> lgtbot.GetUserInfoResponse
	2,  // 22: lgtbot.LGTBotService.GetMatchHistory:output_type -> lgtbot.Message
	16, // 23: lgtbot.LGTBotService.UpdateUserInfo:output_type -> lgtbot.UpdateUserInfoResponse
	18, // 24: lgtbot.LGTBotService.RecordChatMessage:output_type -> lgtbot.RecordChatMessageResponse
	21, // 25: lgtbot.LGTBotService.GetGameList:output_type -> lgtbot.GetGameListResponse
	23, // 26: lgtbot.LGTBotService.StartGame:output_type -> lgtbot.StartGameResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_lgtbot_service_proto_init() }
func file_lgtbot_service_proto_init() {
	if File_lgtbot_service_proto != nil {
		return
	}
	file_command_args_proto_init()
	file_lgtbot_service_proto_msgTypes[1].OneofWrappers = []any{
		(*MsgItem_Text)(nil),
		(*MsgItem_Image)(nil),
		(*MsgItem_AtPlatformUserId)(nil),
		(*MsgItem_Html)(nil),
	}
	file_lgtbot_service_proto_msgTypes[9].OneofWrappers = []any{
		(*PushEvent_PlatformUserId)(nil),
		(*PushEvent_PlatformGroupId)(nil),
		(*PushEvent_Message)(nil),
		(*PushEvent_MatchStart)(nil),
		(*PushEvent_MatchEnd)(nil),
		(*PushEvent_CommandsUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lgtbot_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lgtbot_service_proto_goTypes,
		DependencyIndexes: file_lgtbot_service_proto_depIdxs,
		MessageInfos:      file_lgtbot_service_proto_msgTypes,
	}.Build()
	File_lgtbot_service_proto = out.File
	file_lgtbot_service_proto_rawDesc = nil
	file_lgtbot_service_proto_goTypes = nil
	file_lgtbot_service_proto_depIdxs = nil
}
