// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: lgtbot_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebTimeRange int32

const (
	WebTimeRange_WEB_TIME_RANGE_MONTH WebTimeRange = 0
	WebTimeRange_WEB_TIME_RANGE_YEAR  WebTimeRange = 1
	WebTimeRange_WEB_TIME_RANGE_ALL   WebTimeRange = 2
)

// Enum value maps for WebTimeRange.
var (
	WebTimeRange_name = map[int32]string{
		0: "WEB_TIME_RANGE_MONTH",
		1: "WEB_TIME_RANGE_YEAR",
		2: "WEB_TIME_RANGE_ALL",
	}
	WebTimeRange_value = map[string]int32{
		"WEB_TIME_RANGE_MONTH": 0,
		"WEB_TIME_RANGE_YEAR":  1,
		"WEB_TIME_RANGE_ALL":   2,
	}
)

func (x WebTimeRange) Enum() *WebTimeRange {
	p := new(WebTimeRange)
	*p = x
	return p
}

func (x WebTimeRange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebTimeRange) Descriptor() protoreflect.EnumDescriptor {
	return file_lgtbot_service_proto_enumTypes[0].Descriptor()
}

func (WebTimeRange) Type() protoreflect.EnumType {
	return &file_lgtbot_service_proto_enumTypes[0]
}

func (x WebTimeRange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebTimeRange.Descriptor instead.
func (WebTimeRange) EnumDescriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{0}
}

// ===== Common =====
type ImageMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	DeleteAfterSend bool                   `protobuf:"varint,2,opt,name=delete_after_send,json=deleteAfterSend,proto3" json:"delete_after_send,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImageMsg) Reset() {
	*x = ImageMsg{}
	mi := &file_lgtbot_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMsg) ProtoMessage() {}

func (x *ImageMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMsg.ProtoReflect.Descriptor instead.
func (*ImageMsg) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{0}
}

func (x *ImageMsg) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageMsg) GetDeleteAfterSend() bool {
	if x != nil {
		return x.DeleteAfterSend
	}
	return false
}

type MsgItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*MsgItem_Text
	//	*MsgItem_Image
	//	*MsgItem_AtPlatformUserId
	//	*MsgItem_Html
	Msg           isMsgItem_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgItem) Reset() {
	*x = MsgItem{}
	mi := &file_lgtbot_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgItem) ProtoMessage() {}

func (x *MsgItem) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgItem.ProtoReflect.Descriptor instead.
func (*MsgItem) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{1}
}

func (x *MsgItem) GetMsg() isMsgItem_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MsgItem) GetText() string {
	if x != nil {
		if x, ok := x.Msg.(*MsgItem_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *MsgItem) GetImage() *ImageMsg {
	if x != nil {
		if x, ok := x.Msg.(*MsgItem_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *MsgItem) GetAtPlatformUserId() string {
	if x != nil {
		if x, ok := x.Msg.(*MsgItem_AtPlatformUserId); ok {
			return x.AtPlatformUserId
		}
	}
	return ""
}

func (x *MsgItem) GetHtml() string {
	if x != nil {
		if x, ok := x.Msg.(*MsgItem_Html); ok {
			return x.Html
		}
	}
	return ""
}

type isMsgItem_Msg interface {
	isMsgItem_Msg()
}

type MsgItem_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type MsgItem_Image struct {
	Image *ImageMsg `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type MsgItem_AtPlatformUserId struct {
	AtPlatformUserId string `protobuf:"bytes,3,opt,name=at_platform_user_id,json=atPlatformUserId,proto3,oneof"`
}

type MsgItem_Html struct {
	Html string `protobuf:"bytes,4,opt,name=html,proto3,oneof"`
}

func (*MsgItem_Text) isMsgItem_Msg() {}

func (*MsgItem_Image) isMsgItem_Msg() {}

func (*MsgItem_AtPlatformUserId) isMsgItem_Msg() {}

func (*MsgItem_Html) isMsgItem_Msg() {}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MsgItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_lgtbot_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetItems() []*MsgItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// ===== HandlePrivateRequest =====
type PrivateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	Text           string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrivateRequest) Reset() {
	*x = PrivateRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateRequest) ProtoMessage() {}

func (x *PrivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateRequest.ProtoReflect.Descriptor instead.
func (*PrivateRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{3}
}

func (x *PrivateRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PrivateRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

func (x *PrivateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PrivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateResponse) Reset() {
	*x = PrivateResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateResponse) ProtoMessage() {}

func (x *PrivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateResponse.ProtoReflect.Descriptor instead.
func (*PrivateResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{4}
}

func (x *PrivateResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *PrivateResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// ===== Subscribe =====
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type MatchStartEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlatformGroupId string                 `protobuf:"bytes,1,opt,name=platform_group_id,json=platformGroupId,proto3" json:"platform_group_id,omitempty"`
	PlatformUserIds []string               `protobuf:"bytes,2,rep,name=platform_user_ids,json=platformUserIds,proto3" json:"platform_user_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchStartEvent) Reset() {
	*x = MatchStartEvent{}
	mi := &file_lgtbot_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartEvent) ProtoMessage() {}

func (x *MatchStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartEvent.ProtoReflect.Descriptor instead.
func (*MatchStartEvent) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{6}
}

func (x *MatchStartEvent) GetPlatformGroupId() string {
	if x != nil {
		return x.PlatformGroupId
	}
	return ""
}

func (x *MatchStartEvent) GetPlatformUserIds() []string {
	if x != nil {
		return x.PlatformUserIds
	}
	return nil
}

type MatchEndEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlatformGroupId string                 `protobuf:"bytes,1,opt,name=platform_group_id,json=platformGroupId,proto3" json:"platform_group_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchEndEvent) Reset() {
	*x = MatchEndEvent{}
	mi := &file_lgtbot_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEndEvent) ProtoMessage() {}

func (x *MatchEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEndEvent.ProtoReflect.Descriptor instead.
func (*MatchEndEvent) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{7}
}

func (x *MatchEndEvent) GetPlatformGroupId() string {
	if x != nil {
		return x.PlatformGroupId
	}
	return ""
}

type CommandsUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CommandDef          `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandsUpdateEvent) Reset() {
	*x = CommandsUpdateEvent{}
	mi := &file_lgtbot_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandsUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandsUpdateEvent) ProtoMessage() {}

func (x *CommandsUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandsUpdateEvent.ProtoReflect.Descriptor instead.
func (*CommandsUpdateEvent) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{8}
}

func (x *CommandsUpdateEvent) GetCommands() []*CommandDef {
	if x != nil {
		return x.Commands
	}
	return nil
}

type PushEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventSign uint64                 `protobuf:"varint,1,opt,name=event_sign,json=eventSign,proto3" json:"event_sign,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*PushEvent_PlatformUserId
	//	*PushEvent_PlatformGroupId
	Target isPushEvent_Target `protobuf_oneof:"target"`
	// Types that are valid to be assigned to Event:
	//
	//	*PushEvent_Message
	//	*PushEvent_MatchStart
	//	*PushEvent_MatchEnd
	//	*PushEvent_CommandsUpdate
	Event         isPushEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEvent) Reset() {
	*x = PushEvent{}
	mi := &file_lgtbot_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEvent) ProtoMessage() {}

func (x *PushEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEvent.ProtoReflect.Descriptor instead.
func (*PushEvent) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{9}
}

func (x *PushEvent) GetEventSign() uint64 {
	if x != nil {
		return x.EventSign
	}
	return 0
}

func (x *PushEvent) GetTarget() isPushEvent_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PushEvent) GetPlatformUserId() string {
	if x != nil {
		if x, ok := x.Target.(*PushEvent_PlatformUserId); ok {
			return x.PlatformUserId
		}
	}
	return ""
}

func (x *PushEvent) GetPlatformGroupId() string {
	if x != nil {
		if x, ok := x.Target.(*PushEvent_PlatformGroupId); ok {
			return x.PlatformGroupId
		}
	}
	return ""
}

func (x *PushEvent) GetEvent() isPushEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *PushEvent) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Event.(*PushEvent_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *PushEvent) GetMatchStart() *MatchStartEvent {
	if x != nil {
		if x, ok := x.Event.(*PushEvent_MatchStart); ok {
			return x.MatchStart
		}
	}
	return nil
}

func (x *PushEvent) GetMatchEnd() *MatchEndEvent {
	if x != nil {
		if x, ok := x.Event.(*PushEvent_MatchEnd); ok {
			return x.MatchEnd
		}
	}
	return nil
}

func (x *PushEvent) GetCommandsUpdate() *CommandsUpdateEvent {
	if x != nil {
		if x, ok := x.Event.(*PushEvent_CommandsUpdate); ok {
			return x.CommandsUpdate
		}
	}
	return nil
}

type isPushEvent_Target interface {
	isPushEvent_Target()
}

type PushEvent_PlatformUserId struct {
	PlatformUserId string `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3,oneof"`
}

type PushEvent_PlatformGroupId struct {
	PlatformGroupId string `protobuf:"bytes,3,opt,name=platform_group_id,json=platformGroupId,proto3,oneof"`
}

func (*PushEvent_PlatformUserId) isPushEvent_Target() {}

func (*PushEvent_PlatformGroupId) isPushEvent_Target() {}

type isPushEvent_Event interface {
	isPushEvent_Event()
}

type PushEvent_Message struct {
	Message *Message `protobuf:"bytes,4,opt,name=message,proto3,oneof"`
}

type PushEvent_MatchStart struct {
	MatchStart *MatchStartEvent `protobuf:"bytes,5,opt,name=match_start,json=matchStart,proto3,oneof"`
}

type PushEvent_MatchEnd struct {
	MatchEnd *MatchEndEvent `protobuf:"bytes,6,opt,name=match_end,json=matchEnd,proto3,oneof"`
}

type PushEvent_CommandsUpdate struct {
	CommandsUpdate *CommandsUpdateEvent `protobuf:"bytes,7,opt,name=commands_update,json=commandsUpdate,proto3,oneof"`
}

func (*PushEvent_Message) isPushEvent_Event() {}

func (*PushEvent_MatchStart) isPushEvent_Event() {}

func (*PushEvent_MatchEnd) isPushEvent_Event() {}

func (*PushEvent_CommandsUpdate) isPushEvent_Event() {}

type GetCommandsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCommandsRequest) Reset() {
	*x = GetCommandsRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandsRequest) ProtoMessage() {}

func (x *GetCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandsRequest.ProtoReflect.Descriptor instead.
func (*GetCommandsRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommandsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetCommandsRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

type GetCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CommandDef          `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandsResponse) Reset() {
	*x = GetCommandsResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandsResponse) ProtoMessage() {}

func (x *GetCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandsResponse.ProtoReflect.Descriptor instead.
func (*GetCommandsResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCommandsResponse) GetCommands() []*CommandDef {
	if x != nil {
		return x.Commands
	}
	return nil
}

type GetUserInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserInfoRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetUserInfoRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserInfoResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetUserInfoResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type GetMatchHistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMatchHistoryRequest) Reset() {
	*x = GetMatchHistoryRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchHistoryRequest) ProtoMessage() {}

func (x *GetMatchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetMatchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetMatchHistoryRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetMatchHistoryRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

type UpdateUserInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarPng      []byte                 `protobuf:"bytes,4,opt,name=avatar_png,json=avatarPng,proto3" json:"avatar_png,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserInfoRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetAvatarPng() []byte {
	if x != nil {
		return x.AvatarPng
	}
	return nil
}

type UpdateUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoResponse) Reset() {
	*x = UpdateUserInfoResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoResponse) ProtoMessage() {}

func (x *UpdateUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{16}
}

type RecordChatMessageRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Platform           string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	FromPlatformUserId string                 `protobuf:"bytes,2,opt,name=from_platform_user_id,json=fromPlatformUserId,proto3" json:"from_platform_user_id,omitempty"`
	Text               string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ToPlatformUserId   string                 `protobuf:"bytes,4,opt,name=to_platform_user_id,json=toPlatformUserId,proto3" json:"to_platform_user_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordChatMessageRequest) Reset() {
	*x = RecordChatMessageRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordChatMessageRequest) ProtoMessage() {}

func (x *RecordChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordChatMessageRequest.ProtoReflect.Descriptor instead.
func (*RecordChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{17}
}

func (x *RecordChatMessageRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RecordChatMessageRequest) GetFromPlatformUserId() string {
	if x != nil {
		return x.FromPlatformUserId
	}
	return ""
}

func (x *RecordChatMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RecordChatMessageRequest) GetToPlatformUserId() string {
	if x != nil {
		return x.ToPlatformUserId
	}
	return ""
}

type RecordChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordChatMessageResponse) Reset() {
	*x = RecordChatMessageResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordChatMessageResponse) ProtoMessage() {}

func (x *RecordChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordChatMessageResponse.ProtoReflect.Descriptor instead.
func (*RecordChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{18}
}

type GetGameListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListRequest) Reset() {
	*x = GetGameListRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListRequest) ProtoMessage() {}

func (x *GetGameListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListRequest.ProtoReflect.Descriptor instead.
func (*GetGameListRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{19}
}

type GameInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Developer   string                 `protobuf:"bytes,2,opt,name=developer,proto3" json:"developer,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MinPlayers  uint32                 `protobuf:"varint,4,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`
	MaxPlayers  uint32                 `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	// Game directory name under games path (ASCII), for stable URLs — e.g. "opencomb".
	ModuleName string `protobuf:"bytes,6,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	// Current live matches in core (same as #赛事列表 granularity).
	LiveNotStarted uint32 `protobuf:"varint,7,opt,name=live_not_started,json=liveNotStarted,proto3" json:"live_not_started,omitempty"`
	LiveInProgress uint32 `protobuf:"varint,8,opt,name=live_in_progress,json=liveInProgress,proto3" json:"live_in_progress,omitempty"`
	// Browser URL served by platform web (same path shape as `/api/game-modules/{module}/icon`).
	IconUrl       string `protobuf:"bytes,9,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	mi := &file_lgtbot_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{20}
}

func (x *GameInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameInfo) GetDeveloper() string {
	if x != nil {
		return x.Developer
	}
	return ""
}

func (x *GameInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GameInfo) GetMinPlayers() uint32 {
	if x != nil {
		return x.MinPlayers
	}
	return 0
}

func (x *GameInfo) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *GameInfo) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *GameInfo) GetLiveNotStarted() uint32 {
	if x != nil {
		return x.LiveNotStarted
	}
	return 0
}

func (x *GameInfo) GetLiveInProgress() uint32 {
	if x != nil {
		return x.LiveInProgress
	}
	return 0
}

func (x *GameInfo) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

type GetGameListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*GameInfo            `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListResponse) Reset() {
	*x = GetGameListResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListResponse) ProtoMessage() {}

func (x *GetGameListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListResponse.ProtoReflect.Descriptor instead.
func (*GetGameListResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetGameListResponse) GetGames() []*GameInfo {
	if x != nil {
		return x.Games
	}
	return nil
}

type WebMatchPlayer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlatformUserId string                 `protobuf:"bytes,1,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	DisplayName    string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl      string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebMatchPlayer) Reset() {
	*x = WebMatchPlayer{}
	mi := &file_lgtbot_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebMatchPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebMatchPlayer) ProtoMessage() {}

func (x *WebMatchPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebMatchPlayer.ProtoReflect.Descriptor instead.
func (*WebMatchPlayer) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{22}
}

func (x *WebMatchPlayer) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

func (x *WebMatchPlayer) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *WebMatchPlayer) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type WebMatchBrief struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MatchId         uint64                 `protobuf:"varint,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	State           int32                  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	RoomLabel       string                 `protobuf:"bytes,3,opt,name=room_label,json=roomLabel,proto3" json:"room_label,omitempty"`
	ConfigText      string                 `protobuf:"bytes,4,opt,name=config_text,json=configText,proto3" json:"config_text,omitempty"`
	RoomCreatedUnix int64                  `protobuf:"varint,5,opt,name=room_created_unix,json=roomCreatedUnix,proto3" json:"room_created_unix,omitempty"`
	GameStartedUnix int64                  `protobuf:"varint,6,opt,name=game_started_unix,json=gameStartedUnix,proto3" json:"game_started_unix,omitempty"`
	Players         []*WebMatchPlayer      `protobuf:"bytes,7,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebMatchBrief) Reset() {
	*x = WebMatchBrief{}
	mi := &file_lgtbot_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebMatchBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebMatchBrief) ProtoMessage() {}

func (x *WebMatchBrief) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebMatchBrief.ProtoReflect.Descriptor instead.
func (*WebMatchBrief) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{23}
}

func (x *WebMatchBrief) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *WebMatchBrief) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *WebMatchBrief) GetRoomLabel() string {
	if x != nil {
		return x.RoomLabel
	}
	return ""
}

func (x *WebMatchBrief) GetConfigText() string {
	if x != nil {
		return x.ConfigText
	}
	return ""
}

func (x *WebMatchBrief) GetRoomCreatedUnix() int64 {
	if x != nil {
		return x.RoomCreatedUnix
	}
	return 0
}

func (x *WebMatchBrief) GetGameStartedUnix() int64 {
	if x != nil {
		return x.GameStartedUnix
	}
	return 0
}

func (x *WebMatchBrief) GetPlayers() []*WebMatchPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

type WebListGameMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	GameName      string                 `protobuf:"bytes,2,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebListGameMatchesRequest) Reset() {
	*x = WebListGameMatchesRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebListGameMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebListGameMatchesRequest) ProtoMessage() {}

func (x *WebListGameMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebListGameMatchesRequest.ProtoReflect.Descriptor instead.
func (*WebListGameMatchesRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{24}
}

func (x *WebListGameMatchesRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *WebListGameMatchesRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *WebListGameMatchesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WebListGameMatchesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type WebListGameMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*WebMatchBrief       `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebListGameMatchesResponse) Reset() {
	*x = WebListGameMatchesResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebListGameMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebListGameMatchesResponse) ProtoMessage() {}

func (x *WebListGameMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebListGameMatchesResponse.ProtoReflect.Descriptor instead.
func (*WebListGameMatchesResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{25}
}

func (x *WebListGameMatchesResponse) GetMatches() []*WebMatchBrief {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *WebListGameMatchesResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WebGetGameRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameName      string                 `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebGetGameRuleRequest) Reset() {
	*x = WebGetGameRuleRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebGetGameRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebGetGameRuleRequest) ProtoMessage() {}

func (x *WebGetGameRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebGetGameRuleRequest.ProtoReflect.Descriptor instead.
func (*WebGetGameRuleRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{26}
}

func (x *WebGetGameRuleRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

type WebGetGameRuleResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PureRuleMarkdown string                 `protobuf:"bytes,1,opt,name=pure_rule_markdown,json=pureRuleMarkdown,proto3" json:"pure_rule_markdown,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WebGetGameRuleResponse) Reset() {
	*x = WebGetGameRuleResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebGetGameRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebGetGameRuleResponse) ProtoMessage() {}

func (x *WebGetGameRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebGetGameRuleResponse.ProtoReflect.Descriptor instead.
func (*WebGetGameRuleResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{27}
}

func (x *WebGetGameRuleResponse) GetPureRuleMarkdown() string {
	if x != nil {
		return x.PureRuleMarkdown
	}
	return ""
}

type WebAchievementItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AchievedUserCount uint64                 `protobuf:"varint,3,opt,name=achieved_user_count,json=achievedUserCount,proto3" json:"achieved_user_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WebAchievementItem) Reset() {
	*x = WebAchievementItem{}
	mi := &file_lgtbot_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAchievementItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAchievementItem) ProtoMessage() {}

func (x *WebAchievementItem) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAchievementItem.ProtoReflect.Descriptor instead.
func (*WebAchievementItem) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{28}
}

func (x *WebAchievementItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebAchievementItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WebAchievementItem) GetAchievedUserCount() uint64 {
	if x != nil {
		return x.AchievedUserCount
	}
	return 0
}

type WebGetGameAchievementsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GameName string                 `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	// Used for personal统计字段；可为空则内部用占位 UID 仅取全局达成人数
	ViewerPlatformUserId string `protobuf:"bytes,2,opt,name=viewer_platform_user_id,json=viewerPlatformUserId,proto3" json:"viewer_platform_user_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WebGetGameAchievementsRequest) Reset() {
	*x = WebGetGameAchievementsRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebGetGameAchievementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebGetGameAchievementsRequest) ProtoMessage() {}

func (x *WebGetGameAchievementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebGetGameAchievementsRequest.ProtoReflect.Descriptor instead.
func (*WebGetGameAchievementsRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{29}
}

func (x *WebGetGameAchievementsRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *WebGetGameAchievementsRequest) GetViewerPlatformUserId() string {
	if x != nil {
		return x.ViewerPlatformUserId
	}
	return ""
}

type WebGetGameAchievementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WebAchievementItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebGetGameAchievementsResponse) Reset() {
	*x = WebGetGameAchievementsResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebGetGameAchievementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebGetGameAchievementsResponse) ProtoMessage() {}

func (x *WebGetGameAchievementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebGetGameAchievementsResponse.ProtoReflect.Descriptor instead.
func (*WebGetGameAchievementsResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{30}
}

func (x *WebGetGameAchievementsResponse) GetItems() []*WebAchievementItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type WebRankEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlatformUserId  string                 `protobuf:"bytes,1,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ScoreValue      float64                `protobuf:"fixed64,4,opt,name=score_value,json=scoreValue,proto3" json:"score_value,omitempty"`
	MatchCountValue int64                  `protobuf:"varint,5,opt,name=match_count_value,json=matchCountValue,proto3" json:"match_count_value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebRankEntry) Reset() {
	*x = WebRankEntry{}
	mi := &file_lgtbot_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRankEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRankEntry) ProtoMessage() {}

func (x *WebRankEntry) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRankEntry.ProtoReflect.Descriptor instead.
func (*WebRankEntry) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{31}
}

func (x *WebRankEntry) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

func (x *WebRankEntry) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *WebRankEntry) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *WebRankEntry) GetScoreValue() float64 {
	if x != nil {
		return x.ScoreValue
	}
	return 0
}

func (x *WebRankEntry) GetMatchCountValue() int64 {
	if x != nil {
		return x.MatchCountValue
	}
	return 0
}

type WebGetGameRankingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	GameName      string                 `protobuf:"bytes,2,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	TimeRange     WebTimeRange           `protobuf:"varint,3,opt,name=time_range,json=timeRange,proto3,enum=lgtbot.WebTimeRange" json:"time_range,omitempty"`
	TopN          uint32                 `protobuf:"varint,4,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebGetGameRankingsRequest) Reset() {
	*x = WebGetGameRankingsRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebGetGameRankingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebGetGameRankingsRequest) ProtoMessage() {}

func (x *WebGetGameRankingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebGetGameRankingsRequest.ProtoReflect.Descriptor instead.
func (*WebGetGameRankingsRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{32}
}

func (x *WebGetGameRankingsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *WebGetGameRankingsRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *WebGetGameRankingsRequest) GetTimeRange() WebTimeRange {
	if x != nil {
		return x.TimeRange
	}
	return WebTimeRange_WEB_TIME_RANGE_MONTH
}

func (x *WebGetGameRankingsRequest) GetTopN() uint32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type WebGetGameRankingsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LevelScore         []*WebRankEntry        `protobuf:"bytes,1,rep,name=level_score,json=levelScore,proto3" json:"level_score,omitempty"`
	WeightedLevelScore []*WebRankEntry        `protobuf:"bytes,2,rep,name=weighted_level_score,json=weightedLevelScore,proto3" json:"weighted_level_score,omitempty"`
	MatchCount         []*WebRankEntry        `protobuf:"bytes,3,rep,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WebGetGameRankingsResponse) Reset() {
	*x = WebGetGameRankingsResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebGetGameRankingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebGetGameRankingsResponse) ProtoMessage() {}

func (x *WebGetGameRankingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebGetGameRankingsResponse.ProtoReflect.Descriptor instead.
func (*WebGetGameRankingsResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{33}
}

func (x *WebGetGameRankingsResponse) GetLevelScore() []*WebRankEntry {
	if x != nil {
		return x.LevelScore
	}
	return nil
}

func (x *WebGetGameRankingsResponse) GetWeightedLevelScore() []*WebRankEntry {
	if x != nil {
		return x.WeightedLevelScore
	}
	return nil
}

func (x *WebGetGameRankingsResponse) GetMatchCount() []*WebRankEntry {
	if x != nil {
		return x.MatchCount
	}
	return nil
}

type WebGameLevelRow struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GameName        string                 `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	Count           uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	TotalLevelScore float64                `protobuf:"fixed64,3,opt,name=total_level_score,json=totalLevelScore,proto3" json:"total_level_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebGameLevelRow) Reset() {
	*x = WebGameLevelRow{}
	mi := &file_lgtbot_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebGameLevelRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebGameLevelRow) ProtoMessage() {}

func (x *WebGameLevelRow) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebGameLevelRow.ProtoReflect.Descriptor instead.
func (*WebGameLevelRow) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{34}
}

func (x *WebGameLevelRow) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *WebGameLevelRow) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *WebGameLevelRow) GetTotalLevelScore() float64 {
	if x != nil {
		return x.TotalLevelScore
	}
	return 0
}

type WebRecentMatchRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameName      string                 `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	FinishTime    string                 `protobuf:"bytes,2,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	UserCount     int64                  `protobuf:"varint,3,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	Multiple      uint32                 `protobuf:"varint,4,opt,name=multiple,proto3" json:"multiple,omitempty"`
	GameScore     int64                  `protobuf:"varint,5,opt,name=game_score,json=gameScore,proto3" json:"game_score,omitempty"`
	ZeroSumScore  int64                  `protobuf:"varint,6,opt,name=zero_sum_score,json=zeroSumScore,proto3" json:"zero_sum_score,omitempty"`
	TopScore      int64                  `protobuf:"varint,7,opt,name=top_score,json=topScore,proto3" json:"top_score,omitempty"`
	LevelScore    float64                `protobuf:"fixed64,8,opt,name=level_score,json=levelScore,proto3" json:"level_score,omitempty"`
	RankScore     int64                  `protobuf:"varint,9,opt,name=rank_score,json=rankScore,proto3" json:"rank_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRecentMatchRow) Reset() {
	*x = WebRecentMatchRow{}
	mi := &file_lgtbot_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRecentMatchRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRecentMatchRow) ProtoMessage() {}

func (x *WebRecentMatchRow) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRecentMatchRow.ProtoReflect.Descriptor instead.
func (*WebRecentMatchRow) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{35}
}

func (x *WebRecentMatchRow) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *WebRecentMatchRow) GetFinishTime() string {
	if x != nil {
		return x.FinishTime
	}
	return ""
}

func (x *WebRecentMatchRow) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *WebRecentMatchRow) GetMultiple() uint32 {
	if x != nil {
		return x.Multiple
	}
	return 0
}

func (x *WebRecentMatchRow) GetGameScore() int64 {
	if x != nil {
		return x.GameScore
	}
	return 0
}

func (x *WebRecentMatchRow) GetZeroSumScore() int64 {
	if x != nil {
		return x.ZeroSumScore
	}
	return 0
}

func (x *WebRecentMatchRow) GetTopScore() int64 {
	if x != nil {
		return x.TopScore
	}
	return 0
}

func (x *WebRecentMatchRow) GetLevelScore() float64 {
	if x != nil {
		return x.LevelScore
	}
	return 0
}

func (x *WebRecentMatchRow) GetRankScore() int64 {
	if x != nil {
		return x.RankScore
	}
	return 0
}

type WebRecentHonorRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRecentHonorRow) Reset() {
	*x = WebRecentHonorRow{}
	mi := &file_lgtbot_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRecentHonorRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRecentHonorRow) ProtoMessage() {}

func (x *WebRecentHonorRow) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRecentHonorRow.ProtoReflect.Descriptor instead.
func (*WebRecentHonorRow) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{36}
}

func (x *WebRecentHonorRow) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WebRecentHonorRow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WebRecentHonorRow) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type WebRecentAchievementRow struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	GameName               string                 `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	AchievementName        string                 `protobuf:"bytes,2,opt,name=achievement_name,json=achievementName,proto3" json:"achievement_name,omitempty"`
	AchievementDescription string                 `protobuf:"bytes,3,opt,name=achievement_description,json=achievementDescription,proto3" json:"achievement_description,omitempty"`
	Time                   string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WebRecentAchievementRow) Reset() {
	*x = WebRecentAchievementRow{}
	mi := &file_lgtbot_service_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRecentAchievementRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRecentAchievementRow) ProtoMessage() {}

func (x *WebRecentAchievementRow) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRecentAchievementRow.ProtoReflect.Descriptor instead.
func (*WebRecentAchievementRow) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{37}
}

func (x *WebRecentAchievementRow) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *WebRecentAchievementRow) GetAchievementName() string {
	if x != nil {
		return x.AchievementName
	}
	return ""
}

func (x *WebRecentAchievementRow) GetAchievementDescription() string {
	if x != nil {
		return x.AchievementDescription
	}
	return ""
}

func (x *WebRecentAchievementRow) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type WebUserProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	TimeRange      WebTimeRange           `protobuf:"varint,3,opt,name=time_range,json=timeRange,proto3,enum=lgtbot.WebTimeRange" json:"time_range,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebUserProfileRequest) Reset() {
	*x = WebUserProfileRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebUserProfileRequest) ProtoMessage() {}

func (x *WebUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebUserProfileRequest.ProtoReflect.Descriptor instead.
func (*WebUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{38}
}

func (x *WebUserProfileRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *WebUserProfileRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

func (x *WebUserProfileRequest) GetTimeRange() WebTimeRange {
	if x != nil {
		return x.TimeRange
	}
	return WebTimeRange_WEB_TIME_RANGE_MONTH
}

type WebUserProfileResponse struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	TotalZeroSumScore  int64                      `protobuf:"varint,1,opt,name=total_zero_sum_score,json=totalZeroSumScore,proto3" json:"total_zero_sum_score,omitempty"`
	TotalTopScore      int64                      `protobuf:"varint,2,opt,name=total_top_score,json=totalTopScore,proto3" json:"total_top_score,omitempty"`
	MatchCount         int64                      `protobuf:"varint,3,opt,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`
	BirthTime          string                     `protobuf:"bytes,4,opt,name=birth_time,json=birthTime,proto3" json:"birth_time,omitempty"`
	GameLevels         []*WebGameLevelRow         `protobuf:"bytes,5,rep,name=game_levels,json=gameLevels,proto3" json:"game_levels,omitempty"`
	RecentMatches      []*WebRecentMatchRow       `protobuf:"bytes,6,rep,name=recent_matches,json=recentMatches,proto3" json:"recent_matches,omitempty"`
	RecentHonors       []*WebRecentHonorRow       `protobuf:"bytes,7,rep,name=recent_honors,json=recentHonors,proto3" json:"recent_honors,omitempty"`
	RecentAchievements []*WebRecentAchievementRow `protobuf:"bytes,8,rep,name=recent_achievements,json=recentAchievements,proto3" json:"recent_achievements,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WebUserProfileResponse) Reset() {
	*x = WebUserProfileResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebUserProfileResponse) ProtoMessage() {}

func (x *WebUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebUserProfileResponse.ProtoReflect.Descriptor instead.
func (*WebUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{39}
}

func (x *WebUserProfileResponse) GetTotalZeroSumScore() int64 {
	if x != nil {
		return x.TotalZeroSumScore
	}
	return 0
}

func (x *WebUserProfileResponse) GetTotalTopScore() int64 {
	if x != nil {
		return x.TotalTopScore
	}
	return 0
}

func (x *WebUserProfileResponse) GetMatchCount() int64 {
	if x != nil {
		return x.MatchCount
	}
	return 0
}

func (x *WebUserProfileResponse) GetBirthTime() string {
	if x != nil {
		return x.BirthTime
	}
	return ""
}

func (x *WebUserProfileResponse) GetGameLevels() []*WebGameLevelRow {
	if x != nil {
		return x.GameLevels
	}
	return nil
}

func (x *WebUserProfileResponse) GetRecentMatches() []*WebRecentMatchRow {
	if x != nil {
		return x.RecentMatches
	}
	return nil
}

func (x *WebUserProfileResponse) GetRecentHonors() []*WebRecentHonorRow {
	if x != nil {
		return x.RecentHonors
	}
	return nil
}

func (x *WebUserProfileResponse) GetRecentAchievements() []*WebRecentAchievementRow {
	if x != nil {
		return x.RecentAchievements
	}
	return nil
}

type StartGameRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,2,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	GameName       string                 `protobuf:"bytes,3,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	Solo           bool                   `protobuf:"varint,4,opt,name=solo,proto3" json:"solo,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_lgtbot_service_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{40}
}

func (x *StartGameRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *StartGameRequest) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

func (x *StartGameRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *StartGameRequest) GetSolo() bool {
	if x != nil {
		return x.Solo
	}
	return false
}

type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_lgtbot_service_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lgtbot_service_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_lgtbot_service_proto_rawDescGZIP(), []int{41}
}

func (x *StartGameResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *StartGameResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_lgtbot_service_proto protoreflect.FileDescriptor

const file_lgtbot_service_proto_rawDesc = "" +
	"\n" +
	"\x14lgtbot_service.proto\x12\x06lgtbot\x1a\x12command_args.proto\"H\n" +
	"\bImageMsg\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12*\n" +
	"\x11delete_after_send\x18\x02 \x01(\bR\x0fdeleteAfterSend\"\x97\x01\n" +
	"\aMsgItem\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12(\n" +
	"\x05image\x18\x02 \x01(\v2\x10.lgtbot.ImageMsgH\x00R\x05image\x12/\n" +
	"\x13at_platform_user_id\x18\x03 \x01(\tH\x00R\x10atPlatformUserId\x12\x14\n" +
	"\x04html\x18\x04 \x01(\tH\x00R\x04htmlB\x05\n" +
	"\x03msg\"0\n" +
	"\aMessage\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.lgtbot.MsgItemR\x05items\"j\n" +
	"\x0ePrivateRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12(\n" +
	"\x10platform_user_id\x18\x02 \x01(\tR\x0eplatformUserId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"E\n" +
	"\x0fPrivateResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\".\n" +
	"\x10SubscribeRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\"i\n" +
	"\x0fMatchStartEvent\x12*\n" +
	"\x11platform_group_id\x18\x01 \x01(\tR\x0fplatformGroupId\x12*\n" +
	"\x11platform_user_ids\x18\x02 \x03(\tR\x0fplatformUserIds\";\n" +
	"\rMatchEndEvent\x12*\n" +
	"\x11platform_group_id\x18\x01 \x01(\tR\x0fplatformGroupId\"E\n" +
	"\x13CommandsUpdateEvent\x12.\n" +
	"\bcommands\x18\x01 \x03(\v2\x12.lgtbot.CommandDefR\bcommands\"\xfe\x02\n" +
	"\tPushEvent\x12\x1d\n" +
	"\n" +
	"event_sign\x18\x01 \x01(\x04R\teventSign\x12*\n" +
	"\x10platform_user_id\x18\x02 \x01(\tH\x00R\x0eplatformUserId\x12,\n" +
	"\x11platform_group_id\x18\x03 \x01(\tH\x00R\x0fplatformGroupId\x12+\n" +
	"\amessage\x18\x04 \x01(\v2\x0f.lgtbot.MessageH\x01R\amessage\x12:\n" +
	"\vmatch_start\x18\x05 \x01(\v2\x17.lgtbot.MatchStartEventH\x01R\n" +
	"matchStart\x124\n" +
	"\tmatch_end\x18\x06 \x01(\v2\x15.lgtbot.MatchEndEventH\x01R\bmatchEnd\x12F\n" +
	"\x0fcommands_update\x18\a \x01(\v2\x1b.lgtbot.CommandsUpdateEventH\x01R\x0ecommandsUpdateB\b\n" +
	"\x06targetB\a\n" +
	"\x05event\"Z\n" +
	"\x12GetCommandsRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12(\n" +
	"\x10platform_user_id\x18\x02 \x01(\tR\x0eplatformUserId\"E\n" +
	"\x13GetCommandsResponse\x12.\n" +
	"\bcommands\x18\x01 \x03(\v2\x12.lgtbot.CommandDefR\bcommands\"Z\n" +
	"\x12GetUserInfoRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12(\n" +
	"\x10platform_user_id\x18\x02 \x01(\tR\x0eplatformUserId\"W\n" +
	"\x13GetUserInfoResponse\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tR\tavatarUrl\"^\n" +
	"\x16GetMatchHistoryRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12(\n" +
	"\x10platform_user_id\x18\x02 \x01(\tR\x0eplatformUserId\"\x9f\x01\n" +
	"\x15UpdateUserInfoRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12(\n" +
	"\x10platform_user_id\x18\x02 \x01(\tR\x0eplatformUserId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_png\x18\x04 \x01(\fR\tavatarPng\"\x18\n" +
	"\x16UpdateUserInfoResponse\"\xac\x01\n" +
	"\x18RecordChatMessageRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x121\n" +
	"\x15from_platform_user_id\x18\x02 \x01(\tR\x12fromPlatformUserId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12-\n" +
	"\x13to_platform_user_id\x18\x04 \x01(\tR\x10toPlatformUserId\"\x1b\n" +
	"\x19RecordChatMessageResponse\"\x14\n" +
	"\x12GetGameListRequest\"\xb0\x02\n" +
	"\bGameInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdeveloper\x18\x02 \x01(\tR\tdeveloper\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vmin_players\x18\x04 \x01(\rR\n" +
	"minPlayers\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\rR\n" +
	"maxPlayers\x12\x1f\n" +
	"\vmodule_name\x18\x06 \x01(\tR\n" +
	"moduleName\x12(\n" +
	"\x10live_not_started\x18\a \x01(\rR\x0eliveNotStarted\x12(\n" +
	"\x10live_in_progress\x18\b \x01(\rR\x0eliveInProgress\x12\x19\n" +
	"\bicon_url\x18\t \x01(\tR\aiconUrl\"=\n" +
	"\x13GetGameListResponse\x12&\n" +
	"\x05games\x18\x01 \x03(\v2\x10.lgtbot.GameInfoR\x05games\"|\n" +
	"\x0eWebMatchPlayer\x12(\n" +
	"\x10platform_user_id\x18\x01 \x01(\tR\x0eplatformUserId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"\x8a\x02\n" +
	"\rWebMatchBrief\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\x04R\amatchId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\x12\x1d\n" +
	"\n" +
	"room_label\x18\x03 \x01(\tR\troomLabel\x12\x1f\n" +
	"\vconfig_text\x18\x04 \x01(\tR\n" +
	"configText\x12*\n" +
	"\x11room_created_unix\x18\x05 \x01(\x03R\x0froomCreatedUnix\x12*\n" +
	"\x11game_started_unix\x18\x06 \x01(\x03R\x0fgameStartedUnix\x120\n" +
	"\aplayers\x18\a \x03(\v2\x16.lgtbot.WebMatchPlayerR\aplayers\"\x82\x01\n" +
	"\x19WebListGameMatchesRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1b\n" +
	"\tgame_name\x18\x02 \x01(\tR\bgameName\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"c\n" +
	"\x1aWebListGameMatchesResponse\x12/\n" +
	"\amatches\x18\x01 \x03(\v2\x15.lgtbot.WebMatchBriefR\amatches\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"4\n" +
	"\x15WebGetGameRuleRequest\x12\x1b\n" +
	"\tgame_name\x18\x01 \x01(\tR\bgameName\"F\n" +
	"\x16WebGetGameRuleResponse\x12,\n" +
	"\x12pure_rule_markdown\x18\x01 \x01(\tR\x10pureRuleMarkdown\"z\n" +
	"\x12WebAchievementItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12.\n" +
	"\x13achieved_user_count\x18\x03 \x01(\x04R\x11achievedUserCount\"s\n" +
	"\x1dWebGetGameAchievementsRequest\x12\x1b\n" +
	"\tgame_name\x18\x01 \x01(\tR\bgameName\x125\n" +
	"\x17viewer_platform_user_id\x18\x02 \x01(\tR\x14viewerPlatformUserId\"R\n" +
	"\x1eWebGetGameAchievementsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.lgtbot.WebAchievementItemR\x05items\"\xc7\x01\n" +
	"\fWebRankEntry\x12(\n" +
	"\x10platform_user_id\x18\x01 \x01(\tR\x0eplatformUserId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x1f\n" +
	"\vscore_value\x18\x04 \x01(\x01R\n" +
	"scoreValue\x12*\n" +
	"\x11match_count_value\x18\x05 \x01(\x03R\x0fmatchCountValue\"\x9e\x01\n" +
	"\x19WebGetGameRankingsRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1b\n" +
	"\tgame_name\x18\x02 \x01(\tR\bgameName\x123\n" +
	"\n" +
	"time_range\x18\x03 \x01(\x0e2\x14.lgtbot.WebTimeRangeR\ttimeRange\x12\x13\n" +
	"\x05top_n\x18\x04 \x01(\rR\x04topN\"\xd2\x01\n" +
	"\x1aWebGetGameRankingsResponse\x125\n" +
	"\vlevel_score\x18\x01 \x03(\v2\x14.lgtbot.WebRankEntryR\n" +
	"levelScore\x12F\n" +
	"\x14weighted_level_score\x18\x02 \x03(\v2\x14.lgtbot.WebRankEntryR\x12weightedLevelScore\x125\n" +
	"\vmatch_count\x18\x03 \x03(\v2\x14.lgtbot.WebRankEntryR\n" +
	"matchCount\"p\n" +
	"\x0fWebGameLevelRow\x12\x1b\n" +
	"\tgame_name\x18\x01 \x01(\tR\bgameName\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12*\n" +
	"\x11total_level_score\x18\x03 \x01(\x01R\x0ftotalLevelScore\"\xae\x02\n" +
	"\x11WebRecentMatchRow\x12\x1b\n" +
	"\tgame_name\x18\x01 \x01(\tR\bgameName\x12\x1f\n" +
	"\vfinish_time\x18\x02 \x01(\tR\n" +
	"finishTime\x12\x1d\n" +
	"\n" +
	"user_count\x18\x03 \x01(\x03R\tuserCount\x12\x1a\n" +
	"\bmultiple\x18\x04 \x01(\rR\bmultiple\x12\x1d\n" +
	"\n" +
	"game_score\x18\x05 \x01(\x03R\tgameScore\x12$\n" +
	"\x0ezero_sum_score\x18\x06 \x01(\x03R\fzeroSumScore\x12\x1b\n" +
	"\ttop_score\x18\a \x01(\x03R\btopScore\x12\x1f\n" +
	"\vlevel_score\x18\b \x01(\x01R\n" +
	"levelScore\x12\x1d\n" +
	"\n" +
	"rank_score\x18\t \x01(\x03R\trankScore\"Y\n" +
	"\x11WebRecentHonorRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\"\xae\x01\n" +
	"\x17WebRecentAchievementRow\x12\x1b\n" +
	"\tgame_name\x18\x01 \x01(\tR\bgameName\x12)\n" +
	"\x10achievement_name\x18\x02 \x01(\tR\x0fachievementName\x127\n" +
	"\x17achievement_description\x18\x03 \x01(\tR\x16achievementDescription\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\"\x92\x01\n" +
	"\x15WebUserProfileRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12(\n" +
	"\x10platform_user_id\x18\x02 \x01(\tR\x0eplatformUserId\x123\n" +
	"\n" +
	"time_range\x18\x03 \x01(\x0e2\x14.lgtbot.WebTimeRangeR\ttimeRange\"\xbf\x03\n" +
	"\x16WebUserProfileResponse\x12/\n" +
	"\x14total_zero_sum_score\x18\x01 \x01(\x03R\x11totalZeroSumScore\x12&\n" +
	"\x0ftotal_top_score\x18\x02 \x01(\x03R\rtotalTopScore\x12\x1f\n" +
	"\vmatch_count\x18\x03 \x01(\x03R\n" +
	"matchCount\x12\x1d\n" +
	"\n" +
	"birth_time\x18\x04 \x01(\tR\tbirthTime\x128\n" +
	"\vgame_levels\x18\x05 \x03(\v2\x17.lgtbot.WebGameLevelRowR\n" +
	"gameLevels\x12@\n" +
	"\x0erecent_matches\x18\x06 \x03(\v2\x19.lgtbot.WebRecentMatchRowR\rrecentMatches\x12>\n" +
	"\rrecent_honors\x18\a \x03(\v2\x19.lgtbot.WebRecentHonorRowR\frecentHonors\x12P\n" +
	"\x13recent_achievements\x18\b \x03(\v2\x1f.lgtbot.WebRecentAchievementRowR\x12recentAchievements\"\x89\x01\n" +
	"\x10StartGameRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12(\n" +
	"\x10platform_user_id\x18\x02 \x01(\tR\x0eplatformUserId\x12\x1b\n" +
	"\tgame_name\x18\x03 \x01(\tR\bgameName\x12\x12\n" +
	"\x04solo\x18\x04 \x01(\bR\x04solo\"G\n" +
	"\x11StartGameResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg*Y\n" +
	"\fWebTimeRange\x12\x18\n" +
	"\x14WEB_TIME_RANGE_MONTH\x10\x00\x12\x17\n" +
	"\x13WEB_TIME_RANGE_YEAR\x10\x01\x12\x16\n" +
	"\x12WEB_TIME_RANGE_ALL\x10\x022\xe4\b\n" +
	"\rLGTBotService\x12G\n" +
	"\x14HandlePrivateRequest\x12\x16.lgtbot.PrivateRequest\x1a\x17.lgtbot.PrivateResponse\x12:\n" +
	"\tSubscribe\x12\x18.lgtbot.SubscribeRequest\x1a\x11.lgtbot.PushEvent0\x01\x12F\n" +
	"\vGetCommands\x12\x1a.lgtbot.GetCommandsRequest\x1a\x1b.lgtbot.GetCommandsResponse\x12F\n" +
	"\vGetUserInfo\x12\x1a.lgtbot.GetUserInfoRequest\x1a\x1b.lgtbot.GetUserInfoResponse\x12D\n" +
	"\x0fGetMatchHistory\x12\x1e.lgtbot.GetMatchHistoryRequest\x1a\x0f.lgtbot.Message0\x01\x12O\n" +
	"\x0eUpdateUserInfo\x12\x1d.lgtbot.UpdateUserInfoRequest\x1a\x1e.lgtbot.UpdateUserInfoResponse\x12X\n" +
	"\x11RecordChatMessage\x12 .lgtbot.RecordChatMessageRequest\x1a!.lgtbot.RecordChatMessageResponse\x12F\n" +
	"\vGetGameList\x12\x1a.lgtbot.GetGameListRequest\x1a\x1b.lgtbot.GetGameListResponse\x12@\n" +
	"\tStartGame\x12\x18.lgtbot.StartGameRequest\x1a\x19.lgtbot.StartGameResponse\x12[\n" +
	"\x12WebListGameMatches\x12!.lgtbot.WebListGameMatchesRequest\x1a\".lgtbot.WebListGameMatchesResponse\x12O\n" +
	"\x0eWebGetGameRule\x12\x1d.lgtbot.WebGetGameRuleRequest\x1a\x1e.lgtbot.WebGetGameRuleResponse\x12g\n" +
	"\x16WebGetGameAchievements\x12%.lgtbot.WebGetGameAchievementsRequest\x1a&.lgtbot.WebGetGameAchievementsResponse\x12[\n" +
	"\x12WebGetGameRankings\x12!.lgtbot.WebGetGameRankingsRequest\x1a\".lgtbot.WebGetGameRankingsResponse\x12O\n" +
	"\x0eWebUserProfile\x12\x1d.lgtbot.WebUserProfileRequest\x1a\x1e.lgtbot.WebUserProfileResponseB\x14Z\x12lgtbot/proto/pb;pbb\x06proto3"

var (
	file_lgtbot_service_proto_rawDescOnce sync.Once
	file_lgtbot_service_proto_rawDescData []byte
)

func file_lgtbot_service_proto_rawDescGZIP() []byte {
	file_lgtbot_service_proto_rawDescOnce.Do(func() {
		file_lgtbot_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lgtbot_service_proto_rawDesc), len(file_lgtbot_service_proto_rawDesc)))
	})
	return file_lgtbot_service_proto_rawDescData
}

var file_lgtbot_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lgtbot_service_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_lgtbot_service_proto_goTypes = []any{
	(WebTimeRange)(0),                      // 0: lgtbot.WebTimeRange
	(*ImageMsg)(nil),                       // 1: lgtbot.ImageMsg
	(*MsgItem)(nil),                        // 2: lgtbot.MsgItem
	(*Message)(nil),                        // 3: lgtbot.Message
	(*PrivateRequest)(nil),                 // 4: lgtbot.PrivateRequest
	(*PrivateResponse)(nil),                // 5: lgtbot.PrivateResponse
	(*SubscribeRequest)(nil),               // 6: lgtbot.SubscribeRequest
	(*MatchStartEvent)(nil),                // 7: lgtbot.MatchStartEvent
	(*MatchEndEvent)(nil),                  // 8: lgtbot.MatchEndEvent
	(*CommandsUpdateEvent)(nil),            // 9: lgtbot.CommandsUpdateEvent
	(*PushEvent)(nil),                      // 10: lgtbot.PushEvent
	(*GetCommandsRequest)(nil),             // 11: lgtbot.GetCommandsRequest
	(*GetCommandsResponse)(nil),            // 12: lgtbot.GetCommandsResponse
	(*GetUserInfoRequest)(nil),             // 13: lgtbot.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),            // 14: lgtbot.GetUserInfoResponse
	(*GetMatchHistoryRequest)(nil),         // 15: lgtbot.GetMatchHistoryRequest
	(*UpdateUserInfoRequest)(nil),          // 16: lgtbot.UpdateUserInfoRequest
	(*UpdateUserInfoResponse)(nil),         // 17: lgtbot.UpdateUserInfoResponse
	(*RecordChatMessageRequest)(nil),       // 18: lgtbot.RecordChatMessageRequest
	(*RecordChatMessageResponse)(nil),      // 19: lgtbot.RecordChatMessageResponse
	(*GetGameListRequest)(nil),             // 20: lgtbot.GetGameListRequest
	(*GameInfo)(nil),                       // 21: lgtbot.GameInfo
	(*GetGameListResponse)(nil),            // 22: lgtbot.GetGameListResponse
	(*WebMatchPlayer)(nil),                 // 23: lgtbot.WebMatchPlayer
	(*WebMatchBrief)(nil),                  // 24: lgtbot.WebMatchBrief
	(*WebListGameMatchesRequest)(nil),      // 25: lgtbot.WebListGameMatchesRequest
	(*WebListGameMatchesResponse)(nil),     // 26: lgtbot.WebListGameMatchesResponse
	(*WebGetGameRuleRequest)(nil),          // 27: lgtbot.WebGetGameRuleRequest
	(*WebGetGameRuleResponse)(nil),         // 28: lgtbot.WebGetGameRuleResponse
	(*WebAchievementItem)(nil),             // 29: lgtbot.WebAchievementItem
	(*WebGetGameAchievementsRequest)(nil),  // 30: lgtbot.WebGetGameAchievementsRequest
	(*WebGetGameAchievementsResponse)(nil), // 31: lgtbot.WebGetGameAchievementsResponse
	(*WebRankEntry)(nil),                   // 32: lgtbot.WebRankEntry
	(*WebGetGameRankingsRequest)(nil),      // 33: lgtbot.WebGetGameRankingsRequest
	(*WebGetGameRankingsResponse)(nil),     // 34: lgtbot.WebGetGameRankingsResponse
	(*WebGameLevelRow)(nil),                // 35: lgtbot.WebGameLevelRow
	(*WebRecentMatchRow)(nil),              // 36: lgtbot.WebRecentMatchRow
	(*WebRecentHonorRow)(nil),              // 37: lgtbot.WebRecentHonorRow
	(*WebRecentAchievementRow)(nil),        // 38: lgtbot.WebRecentAchievementRow
	(*WebUserProfileRequest)(nil),          // 39: lgtbot.WebUserProfileRequest
	(*WebUserProfileResponse)(nil),         // 40: lgtbot.WebUserProfileResponse
	(*StartGameRequest)(nil),               // 41: lgtbot.StartGameRequest
	(*StartGameResponse)(nil),              // 42: lgtbot.StartGameResponse
	(*CommandDef)(nil),                     // 43: lgtbot.CommandDef
}
var file_lgtbot_service_proto_depIdxs = []int32{
	1,  // 0: lgtbot.MsgItem.image:type_name -> lgtbot.ImageMsg
	2,  // 1: lgtbot.Message.items:type_name -> lgtbot.MsgItem
	43, // 2: lgtbot.CommandsUpdateEvent.commands:type_name -> lgtbot.CommandDef
	3,  // 3: lgtbot.PushEvent.message:type_name -> lgtbot.Message
	7,  // 4: lgtbot.PushEvent.match_start:type_name -> lgtbot.MatchStartEvent
	8,  // 5: lgtbot.PushEvent.match_end:type_name -> lgtbot.MatchEndEvent
	9,  // 6: lgtbot.PushEvent.commands_update:type_name -> lgtbot.CommandsUpdateEvent
	43, // 7: lgtbot.GetCommandsResponse.commands:type_name -> lgtbot.CommandDef
	21, // 8: lgtbot.GetGameListResponse.games:type_name -> lgtbot.GameInfo
	23, // 9: lgtbot.WebMatchBrief.players:type_name -> lgtbot.WebMatchPlayer
	24, // 10: lgtbot.WebListGameMatchesResponse.matches:type_name -> lgtbot.WebMatchBrief
	29, // 11: lgtbot.WebGetGameAchievementsResponse.items:type_name -> lgtbot.WebAchievementItem
	0,  // 12: lgtbot.WebGetGameRankingsRequest.time_range:type_name -> lgtbot.WebTimeRange
	32, // 13: lgtbot.WebGetGameRankingsResponse.level_score:type_name -> lgtbot.WebRankEntry
	32, // 14: lgtbot.WebGetGameRankingsResponse.weighted_level_score:type_name -> lgtbot.WebRankEntry
	32, // 15: lgtbot.WebGetGameRankingsResponse.match_count:type_name -> lgtbot.WebRankEntry
	0,  // 16: lgtbot.WebUserProfileRequest.time_range:type_name -> lgtbot.WebTimeRange
	35, // 17: lgtbot.WebUserProfileResponse.game_levels:type_name -> lgtbot.WebGameLevelRow
	36, // 18: lgtbot.WebUserProfileResponse.recent_matches:type_name -> lgtbot.WebRecentMatchRow
	37, // 19: lgtbot.WebUserProfileResponse.recent_honors:type_name -> lgtbot.WebRecentHonorRow
	38, // 20: lgtbot.WebUserProfileResponse.recent_achievements:type_name -> lgtbot.WebRecentAchievementRow
	4,  // 21: lgtbot.LGTBotService.HandlePrivateRequest:input_type -> lgtbot.PrivateRequest
	6,  // 22: lgtbot.LGTBotService.Subscribe:input_type -> lgtbot.SubscribeRequest
	11, // 23: lgtbot.LGTBotService.GetCommands:input_type -> lgtbot.GetCommandsRequest
	13, // 24: lgtbot.LGTBotService.GetUserInfo:input_type -> lgtbot.GetUserInfoRequest
	15, // 25: lgtbot.LGTBotService.GetMatchHistory:input_type -> lgtbot.GetMatchHistoryRequest
	16, // 26: lgtbot.LGTBotService.UpdateUserInfo:input_type -> lgtbot.UpdateUserInfoRequest
	18, // 27: lgtbot.LGTBotService.RecordChatMessage:input_type -> lgtbot.RecordChatMessageRequest
	20, // 28: lgtbot.LGTBotService.GetGameList:input_type -> lgtbot.GetGameListRequest
	41, // 29: lgtbot.LGTBotService.StartGame:input_type -> lgtbot.StartGameRequest
	25, // 30: lgtbot.LGTBotService.WebListGameMatches:input_type -> lgtbot.WebListGameMatchesRequest
	27, // 31: lgtbot.LGTBotService.WebGetGameRule:input_type -> lgtbot.WebGetGameRuleRequest
	30, // 32: lgtbot.LGTBotService.WebGetGameAchievements:input_type -> lgtbot.WebGetGameAchievementsRequest
	33, // 33: lgtbot.LGTBotService.WebGetGameRankings:input_type -> lgtbot.WebGetGameRankingsRequest
	39, // 34: lgtbot.LGTBotService.WebUserProfile:input_type -> lgtbot.WebUserProfileRequest
	5,  // 35: lgtbot.LGTBotService.HandlePrivateRequest:output_type -> lgtbot.PrivateResponse
	10, // 36: lgtbot.LGTBotService.Subscribe:output_type -> lgtbot.PushEvent
	12, // 37: lgtbot.LGTBotService.GetCommands:output_type -> lgtbot.GetCommandsResponse
	14, // 38: lgtbot.LGTBotService.GetUserInfo:output_type -> lgtbot.GetUserInfoResponse
	3,  // 39: lgtbot.LGTBotService.GetMatchHistory:output_type -> lgtbot.Message
	17, // 40: lgtbot.LGTBotService.UpdateUserInfo:output_type -> lgtbot.UpdateUserInfoResponse
	19, // 41: lgtbot.LGTBotService.RecordChatMessage:output_type -> lgtbot.RecordChatMessageResponse
	22, // 42: lgtbot.LGTBotService.GetGameList:output_type -> lgtbot.GetGameListResponse
	42, // 43: lgtbot.LGTBotService.StartGame:output_type -> lgtbot.StartGameResponse
	26, // 44: lgtbot.LGTBotService.WebListGameMatches:output_type -> lgtbot.WebListGameMatchesResponse
	28, // 45: lgtbot.LGTBotService.WebGetGameRule:output_type -> lgtbot.WebGetGameRuleResponse
	31, // 46: lgtbot.LGTBotService.WebGetGameAchievements:output_type -> lgtbot.WebGetGameAchievementsResponse
	34, // 47: lgtbot.LGTBotService.WebGetGameRankings:output_type -> lgtbot.WebGetGameRankingsResponse
	40, // 48: lgtbot.LGTBotService.WebUserProfile:output_type -> lgtbot.WebUserProfileResponse
	35, // [35:49] is the sub-list for method output_type
	21, // [21:35] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_lgtbot_service_proto_init() }
func file_lgtbot_service_proto_init() {
	if File_lgtbot_service_proto != nil {
		return
	}
	file_command_args_proto_init()
	file_lgtbot_service_proto_msgTypes[1].OneofWrappers = []any{
		(*MsgItem_Text)(nil),
		(*MsgItem_Image)(nil),
		(*MsgItem_AtPlatformUserId)(nil),
		(*MsgItem_Html)(nil),
	}
	file_lgtbot_service_proto_msgTypes[9].OneofWrappers = []any{
		(*PushEvent_PlatformUserId)(nil),
		(*PushEvent_PlatformGroupId)(nil),
		(*PushEvent_Message)(nil),
		(*PushEvent_MatchStart)(nil),
		(*PushEvent_MatchEnd)(nil),
		(*PushEvent_CommandsUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lgtbot_service_proto_rawDesc), len(file_lgtbot_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lgtbot_service_proto_goTypes,
		DependencyIndexes: file_lgtbot_service_proto_depIdxs,
		EnumInfos:         file_lgtbot_service_proto_enumTypes,
		MessageInfos:      file_lgtbot_service_proto_msgTypes,
	}.Build()
	File_lgtbot_service_proto = out.File
	file_lgtbot_service_proto_goTypes = nil
	file_lgtbot_service_proto_depIdxs = nil
}
